### ISSUE TITLE
r.landscape.evol: Incorrect number of seconds in a day

### ISSUE THREAD

**Issue by Pikamander2** [OSGeo/grass-addons#1080]
Hi there, I used a code search and found an incorrect number of seconds in a day (84600 instead of 86400) listed in one of your files. I recommend fixing it to avoid incorrect timings that could potentially lead to unexpected behavior.

https://github.com/OSGeo/grass-addons/blob/8135b8a7e919e816997f32f710b53a5af48362ce/src/raster/r.landscape.evol/r.landscape.evol.md?plain=1#L441

**Comment by echoix** [comment]
Fortunately, the only two references are for two versions of the docs in r.landscape, and not in the actual code.

Are you willing to make a quick PR for that trivial fix? I'll be happy to review and merge it!
