### ISSUE TITLE
docs: wrong URI in SUBMITTING

### ISSUE THREAD

**Issue by ldesousa** [OSGeo/grass-addons#1102]
The [`SUBMITTING` file](https://github.com/OSGeo/grass-addons/blob/abb96f2b7b50836a0d3e59665cffff75a203f966/SUBMITTING#L1C5-L1C86) is point to a resource that does not exist.

This issue also affects the main README file in this repo (very last section).

**Comment by petrasovaa** [comment]
I think this file should be removed. The contributing.md needs to be updated, see the recent changes in main repo contributing.md file, there was a new style guide added.
