### ISSUE TITLE
r.learn.train: TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#1175]
The CI fails with

```
scripts/r.learn.train:
`TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'`
```

_Originally posted in https://github.com/OSGeo/grass-addons/issues/1162#issuecomment-2277974535_

**Comment by rohannallamadge** [comment]
hello this is my first time , plz assign to me this

**Comment by neteler** [comment]
Thanks for your interest in fixing this issue. Please submit a respective pull request.

**Comment by rohannallamadge** [comment]
sir is my PR successful ?

**Comment by neteler** [comment]
I think it looks good, yet there seems to be an unrelated issue with the automated tests (CI). See your pull request #1180.

**Comment by rohannallamadge** [comment]
sir issues are resolved with automated test (CI) .is it now PR successful?
