### ISSUE TITLE
[Bug] Failure to install db.join

### ISSUE THREAD

**Issue by jradinger** [OSGeo/grass-addons#118]
**Name of the addon**
db.join

**Describe the bug**
Trying to install db.join via the graphical g.extension results in an error. Installing other add-on modules (e.g. r.*) works. I guess it is a problem with the path (*/trunk/*); I don't know where this reference to svn comes from?!
```
Fetching <db.join> from GRASS GIS Addons repository (be patient)...
svn: E170000: URL 'https://github.com/OSGeo/grass-
addons/trunk/grass7/database/db.join' doesn't exist
ERROR: GRASS Addons <db.join> not found
```

**To Reproduce**
```
# Does not work
g.extension extension=db.join 
# Works                                                                           
g.extension extension=r.fuzzy.logic     
```                                        

**System description (please complete the following information):**
GRASS version: 7.9.dev                                                          
Code revision: 8eba412c8                                                        
Build date: 2020-02-27                                                          
Build platform: x86_64-pc-linux-gnu                                             
GDAL: 3.1.0dev-c74609560e                                                       
PROJ: 6.2.1                                                                     
GEOS: 3.8.0                                                                     
SQLite: 3.29.0                                                                  
Python: 3.7.5                                                                   
wxPython: 4.0.6                                                                 
Platform: Linux-5.3.0-40-generic-x86_64-with-Ubuntu-19.10-eoan

**Comment by ninsbl** [comment]
Fixed in g.extension. See: https://github.com/OSGeo/grass/pull/424
