### ISSUE TITLE
[Feat] repo's settings: always show to update the branch, not only on conflicts

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#1201]
@neteler do you have access to this repo's settings to always show to update the branch, not only on conflicts? (Like we have on the grass repo).

_Ursprünglich gepostet von @echoix in https://github.com/OSGeo/grass-addons/pull/1180#issuecomment-2335178542_

**Comment by neteler** [comment]
Yes, will check asap.

**Comment by neteler** [comment]
@echoix @wenzeslaus 

Here (https://github.com/OSGeo/grass/settings/rules) we have:

![image](https://github.com/user-attachments/assets/dc3ea28d-fe35-444a-9e6a-13b0b00979ec)

while in addons (https://github.com/OSGeo/grass-addons/settings/rules) nothing set at all.

> ... repo's settings to always show to update the branch, not only on conflicts

What exactly needs to be set in the addons repo?

**Comment by echoix** [comment]
![image](https://github.com/user-attachments/assets/1261102e-f99a-44f2-b41f-668b01c2eb94)
In the general page

**Comment by neteler** [comment]
Mhh, this is already active:

![image](https://github.com/user-attachments/assets/e0763438-033f-409f-bbdc-4d1d082fb2b7)

**Comment by echoix** [comment]
Ok great! Either it got changed since, or that that PR specifically wasn't checked to allow us (maintainers) updating the branch
