### ISSUE TITLE
i.sentinel.import: mixture of CELL and FCELL in results possible

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#127]
## The problem

When using `i.sentinel.import`, the results are not consistently of CELL type (integer) but become of FCELL type in case of reprojection being necessary.

The reason is, not surprisingly, here:

https://github.com/OSGeo/grass-addons/blob/ba80171955b1b131b30b180058b6ba093cb86638/grass7/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py#L228

This leads to at least three problems:

* output data type is inconsistent
* in case of reprojection, the resulting files are of way larger file size (not really desired)
* mosaics cannot be well generated:

```
r.buildvrt ...
WARNING: Input maptypes are different
WARNING: Input maptypes are different
r.buildvrt complete.
```

## Potential solutions:

* switch to "nearest [neighbor]" in above code line
* keep "bilinear" and add a `r.mapcalc` call with `round()` function
* your idea here

**Comment by ninsbl** [comment]
Probably best adressed together with #123

**Comment by ninsbl** [comment]
#123 made me thinking: bilinear interpolation would alter pixels at the border. That is probably neglectable, but would not it be cleaner to set 0 to NULL before projecting with bilinear interpolation?

**Comment by neteler** [comment]
Generally yes but the problem is that apparently 0 may also occur within the scene pixels... So a global `r.null` call would be a problem here.
