### ISSUE TITLE
Emissivity retrieval problem i.landsat8.swlst

### ISSUE THREAD

**Issue by JacopoRosaRizzotto** [OSGeo/grass-addons#135]
**Name of the addon**
i.landsat8.swlst

**Describe the bug**
When I try to run the addon, an error message terminates the procedure saying: 
"KeyError: 'Cropland'"
 
This error occurs at the end of the following process:

"|i Masking for pixel values <61440> in the Quality Assessment band.
Creating inverted raster MASK...
All subsequent raster operations will be limited to the MASK area. Removing or renaming raster map named 'MASK' will restore raster operations to normal.

|i Rescaling LC08_L1TP_192028_20200315_20200325_01_T1_B10@PERMANENT digital numbers to spectral radiance

|i Converting spectral radiance to at-Satellite Temperature

|i Rescaling LC08_L1TP_192028_20200315_20200325_01_T1_B11@PERMANENT digital numbers to spectral radiance

|i Converting spectral radiance to at-Satellite Temperature
Raster MASK removed
Traceback (most recent call last):
  File "C:\Users\Jacopo e Teo\AppData\Roaming\GRASS7\addons/
scripts/i.landsat8.swlst.py", line 1256, in <module>
    sys.exit(main())
  File "C:\Users\Jacopo e Teo\AppData\Roaming\GRASS7\addons/
scripts/i.landsat8.swlst.py", line 1114, in main
    split_window_lst = SplitWindowLST(emissivity_class)
  File "C:\Users\Jacopo e Teo\AppData\Roaming\GRASS7\addons\
etc\i.landsat8.swlst\split_window_lst.py", line 195, in
__init__
    self.average_lse_mapcalc =
self._build_average_emissivity_mapcalc()
  File "C:\Users\Jacopo e Teo\AppData\Roaming\GRASS7\addons\
etc\i.landsat8.swlst\split_window_lst.py", line 474, in
_build_average_emissivity_mapcalc
    e10_t10, e10_t11 =
self._retrieve_average_emissivities('Cropland')
  File "C:\Users\Jacopo e Teo\AppData\Roaming\GRASS7\addons\
etc\i.landsat8.swlst\split_window_lst.py", line 264, in
_retrieve_average_emissivities
    emissivity_b10 = EMISSIVITIES[emissivity_class].TIRS10"

So it appears it has come problems in retrieving emissivity from land cover class. I used the FROM GLC land cover classification from 2015, but no value of emissivity seems to be associated with the classification, so apparently the algorithm is not able to retrieve it. 

**System description:**
 - Operating System: Windows 10 Pro v. 1903
 - GRASS GIS version: 7.8.2
 - System time and number format set to United States

Thanks in advance.

**Comment by NikosAlexandris** [comment]
@JacopoRosaRizzotto Can you manually check if there is a valid pixel value in the FROM GLC map?

**Comment by NikosAlexandris** [comment]
(By the way, @JacopoRosaRizzotto, best to include the exact command issued in the bug description.)

**Comment by JacopoRosaRizzotto** [comment]
About the data: I am working on the 10E 50N area, retrieved from: http://data.ess.tsinghua.edu.cn/fromglc2015_v1.html 

For what concerns the command issued, I ran the script directly from the GRASS i.landsat8.swlst graphic interface, so I didn't manually send any command, and the only output I received is the one I posted here.
Thanks.

**Comment by NikosAlexandris** [comment]
@JacopoRosaRizzotto In the bottom part of any command-"window" in GRASS GIS' GUI, one can see and copy-paste the command. However, I have never used this add-on through the GUI. It is not available, as far as I know, through the GUI's menus. Is it?

**Comment by JacopoRosaRizzotto** [comment]
Ok, here is the command string in use:

_i.landsat8.swlst mtl="D:\Lavoro\Convenzione Cattolica\Landsat8_150320_USGS\LC08_L1TP_192028_20200315_20200325_01_T1_MTL.txt" b10=LC08_L1TP_192028_20200315_20200325_01_T1_B10@PERMANENT b11=LC08_L1TP_192028_20200315_20200325_01_T1_B11@PERMANENT qab=LC08_L1TP_192028_20200315_20200325_01_T1_BQA@PERMANENT landcover=Classificazione_FROM_GLC_10E_50N@PERMANENT lst=lst window=7_

The add-on is available by accessing the extension repository of GRASS GIS through the GUI. The main add-on windows appears like this:

![image](https://user-images.githubusercontent.com/62991270/78146501-82363980-7432-11ea-9e83-ce49640defd2.png)

**Comment by NikosAlexandris** [comment]
Dear @JacopoRosaRizzotto, sorry for the late reply. Too much work.
I have been given this a try myself and found out there are some if not several stuff to update in the module. So, I can't test it straightforward.

The error is strange. The land cover classes are hardcoded, here: https://github.com/OSGeo/grass-addons/blob/master/grass7/imagery/i.landsat8.swlst/average_emissivity.csv. I remember that this is the file that is read by the module. The classes are the ones from the FROM-GLC nomenclature. So, it must be something else.

Is the region set correctly? But even so, I think the module does this automatically and uses one of the thermal bands to set the region.

Can you verify the land cover map is correctly imported? Can you visualise it in GRASS GIS for example?

**Comment by NikosAlexandris** [comment]
@JacopoRosaRizzotto A series of updates for Python 3 were required. I updated the add-on.
(As messy as it is, looking at it now after so many years... :-D).

Here the LST map mentioned in the first post of this issue: 
![lst_LC08_L1TP_192028_20200315_20200325_01_T1](https://user-images.githubusercontent.com/7046639/84736539-5729a380-afa6-11ea-8bfd-4ceea54b06a6.png)

By the way, the add-on worked in Python 2.

**Comment by neteler** [comment]
> @JacopoRosaRizzotto A series of updates for Python 3 were required. I updated the add-on.

@NikosAlexandris where did you update it? Here I don't see recent changes:
https://github.com/OSGeo/grass-addons/commits/master/grass7/imagery/i.landsat8.swlst

Is there a different  repo?

**Comment by NikosAlexandris** [comment]
> > @JacopoRosaRizzotto A series of updates for Python 3 were required. I updated the add-on.
> 
> @NikosAlexandris where did you update it? Here I don't see recent changes:
> https://github.com/OSGeo/grass-addons/commits/master/grass7/imagery/i.landsat8.swlst
> 
> Is there a different repo?

Yes (actually two synced ones: https://gitlab.com/NikosAlexandris/i.landsat8.swlst and https://github.com/NikosAlexandris/i.landsat8.swlst). The straightforward way to update the _grass-addons_ seems to be to copy-paste the stuff inside it (in the `i.landsat8.swlst` subdirectory) and loose however, the detailed commit history.

I wonder if the GRASS GIS dev team thinks of using submodules, or any other way/technique, to be more flexible when developing individual add-ons.

**Comment by NikosAlexandris** [comment]
See https://github.com/OSGeo/grass-addons/commit/d422fa949351662f22c45eb09777f212a21c2b44

**Comment by neteler** [comment]
> See [d422fa9](https://github.com/OSGeo/grass-addons/commit/d422fa949351662f22c45eb09777f212a21c2b44)

Thanks for the massive update!

**Comment by neteler** [comment]
> > Is there a different repo?
> 
> Yes (actually two synced ones: https://gitlab.com/NikosAlexandris/i.landsat8.swlst and https://github.com/NikosAlexandris/i.landsat8.swlst). The straightforward way to update the _grass-addons_ seems to be to copy-paste the stuff inside it (in the `i.landsat8.swlst` subdirectory) and loose however, the detailed commit history.
> 
> I wonder if the GRASS GIS dev team thinks of using submodules, or any other way/technique, to be more flexible when developing individual add-ons.

Perhaps @wenzeslaus has an idea how to handle that?
