### ISSUE TITLE
i.sentinel.mask should remove all the *_double files

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-addons#140]
`i.sentinel.mask` creates a floating point version of S2 bands for its calculations. 

IMO, it should remove them at exit maybe with a message or so. Think of users processing many S2 scenes with this add-on, then their mapsets (and disks) will be full of undesired intermediate maps.

@RobiFag what do you think?

**Comment by RobiFag** [comment]
Maybe the *_double file can be defined as temp files that are removed at the end of the process by default but they can also be saved using the -t flag.
I put it on my TO DO list..I will make the changes in the next days!

**Comment by veroandreo** [comment]
Thanks, Robi! :)

**Comment by RobiFag** [comment]
@neteler I made changes requested by Vero. Maybe it's a trivial question but, can I push them directly or is it better to open a pull request?

**Comment by veroandreo** [comment]
Ciao @RobiFag, if trivial you could push, but recommended is to commit through PR from a fix/feature branch
