### ISSUE TITLE
[Feature] Enable GH Actions for grass-addons

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#172]
To improve the software quality it would be nice to have GH Actions also in the grass-addons repo.

It might be derived from the settings currently defined in GRASS GIS release_branch_7_8:

https://github.com/OSGeo/grass/tree/releasebranch_7_8/.github/workflows

What do you think (@wenzeslaus)?

**Comment by neteler** [comment]
May I merge 

- https://github.com/OSGeo/grass/commit/555006043e867673b9bc61e8e3f1b5fea5e98922
- https://github.com/OSGeo/grass/commit/34d145cf817361e3fef8934245ca9eb381bb7f71

here? Of course I'd like to preserve authorship somehow...

**Comment by wenzeslaus** [comment]
Unfortunately, this needs little more than just copy pasting the files, but I have similar code in other repos.

I can look at this, but it would be helpful, although not necessary, to have clear idea about what is happening on the current build server. Are the scripts in the repo up to date and complete? I looked at them once, but I was not really able to run them locally.

Also what do you think about testing against different versions? 7.8 branch, master, Ubuntu PPA, ...? Some more important than the others? Is master reasonable? Perhaps @landam and @hellik can add Windows builds?

BTW, co-authorship is recognized on GitHub (and possibly more universally) by `Co-authored-by: name <name@example.com>` at the end of the commit message ([see GitHub:creating-a-commit-with-multiple-authors](https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors)). I think preserving authorship is possible too, but not much relevant here where significant changes are needed anyway.

**Comment by hellik** [comment]
> Also what do you think about testing against different versions? 7.8 branch, master, Ubuntu PPA, ...? Some more important than the others? Is master reasonable? Perhaps @landam and @hellik can add Windows builds?

what do you mean by adding windows builds? building GRASS? building addons?

is there any progress in compiling GRASS with cmake? maybe this would ease windows builds on gh action?

**Comment by wenzeslaus** [comment]
> > ...add Windows builds?
> 
> what do you mean by adding windows builds? building GRASS? building addons?

I guess both would be needed since there is no grass-dev package for Windows, right?

> is there any progress in compiling GRASS with cmake?

There is, but there is no timeline either. On top of that, CMake is just part of the compilation. Please see https://github.com/OSGeo/grass/pull/348 (CMake only, some Windows support in separate PRs).

> maybe this would ease windows builds on gh action?

I don't know. People are using GitHub Actions with other things than CMake (msys, cygwin, ...), so it seems at least possible.

The Windows VMs on GitHub Actions support Windows Docker containers, so one could run the same environment locally if needed (instead of dealing with the VM there).
