### ISSUE TITLE
r.learn.ml2: fails if training_map does not contain category labels

### ISSUE THREAD

**Issue by griembauer** [OSGeo/grass-addons#183]
**Name of the addon**
r.learn.ml2 (r.learn.predict/r.learn.train) 

**Describe the bug**
Not a bug, because it is indicated in the input options for `r.learn.train` that the `training_map` must contain _labelled_ pixels. If they don't have category labels, `r.learn.predict` fails with the following error message: 
```
Traceback (most recent call last):
  File "/root/.grass7/addons/scripts/r.learn.predict", line 172, in <module>
    main()
  File "/root/.grass7/addons/scripts/r.learn.predict", line 167, in main
    r.category(map=output, rules=rules_file, separator="comma")
  File "/usr/local/grass78/etc/python/grass/pygrass/modules/interface/module.py", line 650, in __call__
    return self.run()
  File "/usr/local/grass78/etc/python/grass/pygrass/modules/interface/module.py", line 771, in run
    self.wait()
  File "/usr/local/grass78/etc/python/grass/pygrass/modules/interface/module.py", line 794, in wait
    module=self.name, errors=stderr)
grass.exceptions.CalledModuleError: Module run r.category r.category map=classification_map_5classes_2019 separator=comma rules=/actinia_core/grassdb/dortmund/nrw_19.tmp/23aab7009ad3/2170.0 ended with error
Process ended with non-zero return code -11. See errors in the (error) output.
```
This is because in this case, `class_labels` is not `None`, but an empty dictionary. It would be great if r.learn.ml2 also worked without category labels assigned to `training_map` (also for consistency with r.learn.ml). 

**To Reproduce**
Run `r.learn.train` and `r.learn.predict` using a training_map without category labels.

**System Description**
-GRASS 7.8.4, Linux

**Comment by neteler** [comment]
@stevenpawley do you have any suggestion here?

**Comment by stevenpawley** [comment]
Thanks for reporting - I'll provide a fix for this later today.

**Comment by stevenpawley** [comment]
Should be fixed now in https://github.com/OSGeo/grass-addons/commit/d033fe07998066af5b50ea3b3adb2b587e767a76
