### ISSUE TITLE
[Bug] Compilation error for new version of r.landscape.evol

### ISSUE THREAD

**Issue by isaacullah** [OSGeo/grass-addons#197]
**Name of the addon**
r.landscape.evol

**Describe the bug**
Hi all, I have just added a substantially new version of r.landscape.evol to the repo, but for some reason I cannot get it to install correctly with g.extension. I can't think of any code change that would do this, and I believe I have configured the Makefile and html documentation properly. Here's the error from g.extension, and any suggestions on what to change will be very much appreciated!

```
g.extension extension=r.landscape.evol                                          
Fetching <r.landscape.evol> from GRASS GIS Addons repository (be patient)...
Compiling...
Traceback (most recent call last):
  File "/usr/lib/grass78/tools/g.html2man.py", line 45, in
main
    p.feed(line)
  File "/usr/lib/python3.8/html/parser.py", line 111, in
feed
    self.goahead(0)
  File "/usr/lib/python3.8/html/parser.py", line 173, in
goahead
    k = self.parse_endtag(i)
  File "/usr/lib/python3.8/html/parser.py", line 421, in
parse_endtag
    self.handle_endtag(elem)
  File "/usr/lib/grass78/tools/ghtml.py", line 231, in
handle_endtag
    if self.pop() == tag:
  File "/usr/lib/grass78/tools/ghtml.py", line 185, in pop
    self.excluded = self.excluded_stack.pop()
IndexError: pop from empty list
During handling of the above exception, another exception
occurred:
Traceback (most recent call last):
  File "/usr/lib/grass78/tools/g.html2man.py", line 78, in
<module>
    main()
  File "/usr/lib/grass78/tools/g.html2man.py", line 49, in
main
    (infile, err.lineno, err.offset, err.msg))
AttributeError: 'IndexError' object has no attribute
'lineno'
make: *** [/usr/lib/grass78/include/Make/Html.make:11: /tmp/
grass7-iullah-439490/tmpnphof_e7/r.landscape.evol/docs/man/m
an1/r.landscape.evol.1] Error 1
ERROR: Compilation failed, sorry. Please check above error messages.
```

**To Reproduce**
1. Go to g.extension
2. Raster>  r.landscape.evol
3. Install

**Expected behavior**
Should compile without error.

**System description (please complete the following information):**
 - Linux, Pop!_OS 20.04
 - GRASS GIS version [e.g. 7.8.2]

**Comment by petrasovaa** [comment]
Your manual page needs to be fixed, look at any other manual page of a module and also see https://trac.osgeo.org/grass/wiki/Submitting/Docs

**Comment by isaacullah** [comment]
Aha! Thanks. This is what happens when one hasn't submitted a fully new
module in a long while... I had completely forgotten about the required
sections in the documentation. I will fix and update...

~Isaac

**Comment by neteler** [comment]
The new version of r.landscape.evol compiles for me but I didn't test it.
Can this issue be closed?
