### ISSUE TITLE
[Bug] i.modis.import: unable to import because of wrong parsing of filename

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-addons#245]
i.modis.import fails with:

```
Proccessing <MOD13C2.A2019335.006.2020004224207.hdf> (1/60)...
WARNING: Illegal filename
         <MOD13C2.A2019335.006.single_"CMG_0.05_Deg_Monthly_NIR_reflectance">.
         Character <"> not allowed.
WARNING: Illegal filename
         <MOD13C2.A2019335.006.single_"CMG_0.05_Deg_Monthly_NIR_reflectance">.
         Character <"> not allowed.
ERROR: <MOD13C2.A2019335.006.single_"CMG_0.05_Deg_Monthly_NIR_reflectance">
       is an illegal file name
WARNING: Error during import of
         MOD13C2.A2019335.006.single_"CMG_0.05_Deg_Monthly_NIR_reflectance"
WARNING: Illegal filename
         <MOD13C2.A2019335.006.single_"CMG_0.05_Deg_Monthly_pixel_reliability">.
         Character <"> not allowed.
WARNING: Illegal filename
         <MOD13C2.A2019335.006.single_"CMG_0.05_Deg_Monthly_pixel_reliability">.
         Character <"> not allowed.
ERROR: 
       <MOD13C2.A2019335.006.single_"CMG_0.05_Deg_Monthly_pixel_reliability">
       is an illegal file name
WARNING: Error during import of
         MOD13C2.A2019335.006.single_"CMG_0.05_Deg_Monthly_pixel_reliability"
WARNING: Illegal filename
         <MOD13C2.A2019335.006.single_"CMG_0.05_Deg_Monthly_MIR_reflectance">.
         Character <"> not allowed.
WARNING: Illegal filename
         <MOD13C2.A2019335.006.single_"CMG_0.05_Deg_Monthly_MIR_reflectance">.
         Character <"> not allowed.
ERROR: <MOD13C2.A2019335.006.single_"CMG_0.05_Deg_Monthly_MIR_reflectance">
       is an illegal file name
WARNING: Error during import of
         MOD13C2.A2019335.006.single_"CMG_0.05_Deg_Monthly_MIR_reflectance"
WARNING: Illegal filename
         <MOD13C2.A2019335.006.single_"CMG_0.05_Deg_Monthly_NDVI">.
         Character <"> not allowed.
WARNING: Illegal filename
         <MOD13C2.A2019335.006.single_"CMG_0.05_Deg_Monthly_NDVI">.
         Character <"> not allowed.
ERROR: <MOD13C2.A2019335.006.single_"CMG_0.05_Deg_Monthly_NDVI"> is an
       illegal file name
WARNING: Error during import of
         MOD13C2.A2019335.006.single_"CMG_0.05_Deg_Monthly_NDVI"
```

when trying to import layers of the [MOD13C2](https://lpdaac.usgs.gov/products/mod13c2v006/) product. This used to work before. It seems the parsing is wrongly taking the quotes to build up the output filename and that's an illegal character.

**To Reproduce**
```
i.modis.download settings=$HOME/SETTING product=ndvi_terra_monthly_5600 startday=2015-01-01 endday=2015-03-31 folder=/tmp
i.modis.import files=/tmp/listfileMOD13C2.006.txt spectral="( 1 0 0 0 1 0 1 0 0 0 0 0 1 )"
```

@landam @lucadelu could you have a look at it, please? I downloaded and imported *lst_terra_monthly_5600* without problems, but it seems *ndvi_terra_monthly_5600* has a different scheme for filenames, maybe because it's a global product and not tiled.

**Comment by veroandreo** [comment]
Digging a lil bit more I found out that the problem comes from pyModis, specifically in modis_convert.py for this NDVI MODIS product; i.modis.import just tries to import files created by modis_convert.py that have an invalid filename for GRASS.

Closing as invalid; will open an issue in pyModis

**Comment by veroandreo** [comment]
done in https://github.com/lucadelu/pyModis/issues/128

**Comment by neteler** [comment]
How about removing these `"` chars here with an additional `replace()` operation?:

https://github.com/OSGeo/grass-addons/blob/b3ee5be21535e56495352bc67c68d0ed9456b08f/grass7/imagery/i.modis/i.modis.import/i.modis.import.py#L453

**Comment by veroandreo** [comment]
> How about removing these `"` chars here with an additional `replace()` operation?:
> 
> https://github.com/OSGeo/grass-addons/blob/b3ee5be21535e56495352bc67c68d0ed9456b08f/grass7/imagery/i.modis/i.modis.import/i.modis.import.py#L453

I tried locally, but within the `single` function which is the one I use, but the `"` do not get replaced
