### ISSUE TITLE
[Bug] v.rast.bufferstats python 2 vs python 3 issue

### ISSUE THREAD

**Issue by hansvancalster** [OSGeo/grass-addons#274]
**v.rast.bufferstats.py**

The `unicode()` python 2 function fails for Python 3. It should be replaced by `str()` according to [this porting guide](https://portingguide.readthedocs.io/en/latest/strings.html). After manually replacing `unicode` with `str` on line 339 the problem was gone.

**To Reproduce**
````
g.region -p raster=elevation,geology_30m
v.clip --o -r input=bridges output=bridges_wake
# Tabulate area of land cover map
g.region -p raster=elevation,geology_30m align=geology_30m
v.rast.bufferstats -t input=bridges_wake raster=geology_30m buffers=100,250,500 column_prefix=geology
````
Just taking the example from the manual here. Not tested, but expect it will show same error (see screenshot).

**Expected behavior**
v.rast.bufferstats exits with calculated results

**Screenshots**
![image](https://user-images.githubusercontent.com/18713718/93224009-f2cadb80-f770-11ea-905a-7c03e34ba9a6.png)

**System description (please complete the following information):**
 - Operating System:  Windows 7
 - GRASS GIS version  7.8.3
- details about further software components
````
version=7.8.3
date=2020
revision=8bcecc9a6
build_date=2020-05-05
build_platform=x86_64-w64-mingw32
build_off_t_size=8
libgis_revision=8bcecc9a6
libgis_date=2020-05-05T08:51:50+00:00
proj=6.3.2
gdal=3.0.4
geos=3.8.1
sqlite=3.29.0
````

**Comment by neteler** [comment]
I have added a unicode() compatibility fix for both Python-2 and Python-3.
Please reopen in case the problem persists.

**Comment by hansvancalster** [comment]
Thank you :+1:
