### ISSUE TITLE
r.fill.gaps: compilation warning

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#308]
[r.fill.gaps](https://grass.osgeo.org/grass7/manuals/addons/r.fill.gaps.html) works nicely and fast with a tiny memory footprint.

When compiling it, a warning comes up. As I am not sure how serious it is I bring it up as an issue:

https://github.com/OSGeo/grass-addons/blob/d899a96083678a1cadd9115cf6b3816543ed17cc/grass7/raster/r.fill.gaps/main.c#L164

```
main.c: In function ‘print_weights_matrix’:
main.c:164:57: warning: too many arguments for format [-Wformat-extra-args]
  164 |                              weight_matrix_line_length, "[????] ",
      |                                                         ^~~~~~~~~
```

While at it, also this one may be fixed:
```
main.c: In function ‘main’:
main.c:1025:12: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 1025 |     mapset = G_find_raster(input, "");
      |            ^

```

**Comment by petrasovaa** [comment]
This module was ported to core as r.fill.stats, so this should be probably removed?

**Comment by neteler** [comment]
Ah! (as a ref: https://github.com/OSGeo/grass/commit/1ccb3efc725c0f17a5678f5ff334bb8ea4caf573)
Indeed, there should be at least the usual "DEPRECATED" file which will drop it from the compilation (https://github.com/OSGeo/grass-addons/blob/d899a96083678a1cadd9115cf6b3816543ed17cc/grass7/raster/Makefile#L10)
Then this issue might be closed.
