### ISSUE TITLE
i.sentinel.import does not recognise .jp2 as a supported file format

### ISSUE THREAD

**Issue by h-inge** [OSGeo/grass-addons#313]
I'm trying to read Sentinel2 satellite imagery on GRASS GIS-7.4.4, but when i run the command i get this error:

ERROR 4: `/Volumes/Maxtor/TESI_satellite_imagery/IMMAGINI_DI
_PARTENZA/serie_storica_estate_dic2015-feb2020/S2/summer18-1
9_S2/S2A_MSIL1C_20181205T135101_N0207_R024_T21JVN_20181205T1
64652.SAFE/GRANULE/L1C_T21JVN_A018039_20181205T135104/IMG_DA
TA/T21JVN_20181205T135101_B01.jp2' not recognised as a
supported file format.
Traceback (most recent call last):
  File "/Users/frah/Library/GRASS/7.4/Modules/scripts/i.sent
inel.import", line 267, in <module>
    sys.exit(main())
  File "/Users/frah/Library/GRASS/7.4/Modules/scripts/i.sent
inel.import", line 255, in main
    importer.print_products()
  File "/Users/frah/Library/GRASS/7.4/Modules/scripts/i.sent
inel.import", line 245, in print_products
    self._raster_epsg(f),
  File "/Users/frah/Library/GRASS/7.4/Modules/scripts/i.sent
inel.import", line 197, in _raster_epsg
    srs.ImportFromWkt(dsn.GetProjectionRef())
AttributeError: 'NoneType' object has no attribute
'GetProjectionRef'

I updated gdal to version 3.1.3.
I'll be hugely grateful if anybody can help me to solve this issue. Thank you in advance.

**Comment by neteler** [comment]
Please consider updating to GRASS GIS 7.8.4: https://grass.osgeo.org/news/2020_10_05_grass_gis_7_8_4_released/

**Comment by h-inge** [comment]
> Please consider updating to GRASS GIS 7.8.4: https://grass.osgeo.org/news/2020_10_05_grass_gis_7_8_4_released/

Thank you for the advice. I updated my GRASS GIS to 7.8.4 version and reimported the extension i.sentinel. Now it doesn't find the files it should import, even if the input directory i typed is the exact same I used when i posted the issue (it seems that now it doesn't recognise the .SAFE folder). I'm reporting the error message i get here below:
i.sentinel.import input=/Users/frah/GISDBASE/S2A_MSIL1C_20181205T135101_N0207_R024_T21JVN_20181205T164652.SAFE
ERROR: Nothing found to import. Please check input and pattern_file options.

I also tried to type the inside folder in which the .jp2 imagery files are stored, but it still returns me the same error.

**Comment by h-inge** [comment]
> Please consider updating to GRASS GIS 7.8.4: https://grass.osgeo.org/news/2020_10_05_grass_gis_7_8_4_released/

Thank you so much for the advice. Now it works.
