### ISSUE TITLE
r.in.wcs - malformed result

### ISSUE THREAD

**Issue by ecodiv** [OSGeo/grass-addons#329]
**Name of the addon**
r.in.wcs

**Describe the bug**
When running r.in.wcs, I am getting the error below:

```                                          
/home/paulo/.grass7/addons/scripts/r.in.wcs --verbose url=https://maps.isric.org/mapserv coverage=cec
Importing raster map into GRASS...
Using current grass region
Boundingbox coordinates:
[33.0, 4.45, 39.4583333333333, 14.9]
[West, South, Eest, North]
gdalbuildvrt -te 33.0 4.45 39.4583333333333 14.9 /home/paulo/Data/GRASSdb/latlon/WesternEthiopia/.tmp/HP-Z600/8352.1 /home/paulo/Data/GRASSdb/latlon/WesternEthiopia/.tmp/HP-Z600/8352.0
0...10...20...30...40...50...60...70...80...90...100 - done.
ERROR 1: HTTP error code : 500
ERROR 1: Malformed Result:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at
webmaster@localhost to inform them of the time this error occurred,
and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at maps.isric.org Port 80</address>
</body></html>

Warning 1: Can't open /home/paulo/Data/GRASSdb/latlon/WesternEthiopia/.tmp/HP-Z600/8352.0. Skipping it

ERROR: Generation of VRT-File failed (gdalbuildvrt ERROR). Set verbose-flag for details.
```
**System description (please complete the following information):**
 - Operating System: Ubuntu 20.04
 - GRASS GIS version 7.8.4

**Comment by lucadelu** [comment]
@ecodiv I did some improvements (#340) and now it works for me with my WCS service (http://geodati.fmach.it/production/ows_europe_lst). 

Your WCS service seems to be broken, the request https://maps.isric.org/mapserv?SERVICE=WCS&REQUEST=GetCapabilities&VERSION=1.0.0 fails

**Comment by lucadelu** [comment]
> HI @lucadelu thanks for looking into this. I got it to work using the oswlib library. I am not very familiar with these kind of calls, but perhaps the code below (which works for me) helps to identify what goes wrong?
> 
Yes, you was using the wrong url

`r.in.wcs url=http://maps.isric.org/mapserv?map=/map/cec.map -c` 

work correctly  and return the list of available layers. However 

`r.in.wcs url=http://maps.isric.org/mapserv?map=/map/cec.map coverage=cec_100-200cm_mean --verbose`

return an error, I will investigate later this error

**Comment by ecodiv** [comment]
Seems to be solved
