### ISSUE TITLE
[Bug] Addon manual pages on server: all relative links lack '../' in the URL which leads to 404

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#337]
**Name of the addon**
This affects all addon manuals on the server.

Random example:
https://grass.osgeo.org/grass7/manuals/addons/i.rotate.html

**Describe the bug**

All relative links (to "Keywords", "Topics", "Fullindex" etc.) are lacking `'../'` in the respective URLs which leads to 404 (page not found).

I am unsure if (how?) it could be injected in the generated addon manual pages are properly created in the first place by (maybe) adding further tricks to

https://github.com/OSGeo/grass-addons/blob/master/tools/cronjobs_osgeo_lxd/compile_addons_git.sh

Ideas are welcome.

**Comment by neteler** [comment]
Sorry, wrong PR links cleaned up.
This issue is not solved yet.

**Comment by neteler** [comment]
I'm afraid that the `../` is still not pplied...:

Random addon manual page:
- https://grass.osgeo.org/grass78/manuals/addons/r.scatterplot.html
    - Keywords: ... lack of `../` in the path.

The footer links " Main index | Raster index | Topics index | Keywords index | Graphical index | Full index " are right.

**Comment by tmszi** [comment]
I found problematic Add-On r.object.activelearning.

manual: https://grass.osgeo.org/grass78/manuals/addons/r.object.activelearning.html
compile log: https://grass.osgeo.org/addons/grass7/logs/r.object.activelearning.log

It is interesting that Add-On compilation (r.object.activelearning) at the localhost  work correctly, including the generated html man page.

**Comment by neteler** [comment]
There I are some more, I just checked on the server:
```

neteler@grasslxd:/var/www/code_and_data/grass78/manuals/addons$ l | grep '   0'
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 i.ann.maskrcnn.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 m.eigensystem.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.futures.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.edm.eval.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.denoise.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.cpt2grass.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.agent.rand.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.agent.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.agent.aco.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.learn.ml2.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.green.hydro.structure.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.green.hydro.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.green.hydro.financial.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.green.hydro.delplants.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.green.gshp.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.green.biomassfor.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.pi.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.out.ntv2.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.object.activelearning.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.maxent.lambdas.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.vector.ruggedness.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 r.tri.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 v.sort.points.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 v.mrmr.html
-rw-rw-r-- 1 neteler users       0 Dec 13 06:27 v.feature.algebra.html

```
