### ISSUE TITLE
[Bug] v.surf.icw

### ISSUE THREAD

**Issue by smathermather** [OSGeo/grass-addons#354]
**Name of the addon**
v.surf.icw

**Describe the bug**
v.surf.icw has had it's first line updated to use Python3, but the language of the addon hasn't been ported to python3.

**To Reproduce**
1. Install the plugin
2. Run through the tutorial here: https://grass.osgeo.org/grass78/manuals/addons/v.surf.icw.html
3. See warnings and errors as follows:	
```
Removing anomalies at site positions ...
/home/user/.grass7/addons/scripts/v.surf.icw:151:
SyntaxWarning: "is" with a literal. Did you mean "=="?
  if workers is 1 and "WORKERS" in os.environ:
/home/user/.grass7/addons/scripts/v.surf.icw:287:
SyntaxWarning: "is" with a literal. Did you mean "=="?
  if num % workers is 0:
/home/user/.grass7/addons/scripts/v.surf.icw:294:
SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if proc[i].wait() is not 0:
/home/user/.grass7/addons/scripts/v.surf.icw:313:
SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (i+1) % workers is 0:
/home/user/.grass7/addons/scripts/v.surf.icw:319:
SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if proc[i].wait() is not 0:
/home/user/.grass7/addons/scripts/v.surf.icw:355:
SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (i+1) % workers is 0:
/home/user/.grass7/addons/scripts/v.surf.icw:364:
SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if proc[i].wait() is not 0
:
/home/user/.grass7/addons/scripts/v.surf.icw:456:
SyntaxWarning: "is" with a literal. Did you mean "=="?
  if num % workers is 0:
Traceback (most recent call last):
  File
"/home/user/.grass7/addons/scripts/v.surf.icw",
line 525, in <module>
    main()
  File
"/home/user/.grass7/addons/scripts/v.surf.icw",
line 309, in main
    proc[i] = grass.mapcalc_start("$cost_n_cleansed =
if($cost_n == 0, 0.1, $cost_n)",
  File "/usr/lib/grass78/etc/python/grass/script/raster.py",
line 161, in mapcalc_start
    p.stdin.write(e)
TypeError: a bytes-like object is required, not 'str'
syntax error
Parse error
ERROR: parse error
```

**Expected behavior**
In the flavor of a classic expected behavior bug report: I would expect the module to run successfully. :smile: 

**System description (please complete the following information):**
 - Operating System: `Linux pop-os 5.4.0-7642-generic #46~1598628707~20.04~040157c-Ubuntu SMP Fri Aug 28 18:02:16 UTC  x86_64 x86_64 x86_64 GNU/Linux`
 - GRASS GIS version 7.8.3

```
version=7.8.3
date=2020
revision=exported
build_date=2020-06-21
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=2020-06-21T23:06:24+00:00
libgis_date=2020-06-21T23:06:24+00:00
proj=7.0.1
gdal=3.1.0
geos=3.8.1
sqlite=3.32.3
```

**Comment by smathermather** [comment]
Interestingly, when I clone the repo (rather than just effecting an install) the first line is `#!/usr/bin/env python` rather than `#!/usr/bin/env python3`.

**Comment by smathermather** [comment]
I am drafting an attempted fix here: https://github.com/OSGeo/grass-addons/pull/355

**Comment by neteler** [comment]
> Interestingly, when I clone the repo (rather than just effecting an install) the first line is `#!/usr/bin/env python` rather than `#!/usr/bin/env python3`.

Yes, as the 3 is "injected" by `g.extension` when installing an addon with GRASS GIS 7.8+. See 

https://github.com/OSGeo/grass/blob/16d779acb608802585fe94b034ddab9c7d3cd991/scripts/g.extension/g.extension.py#L1258

Older version will still use `python`(-2) since the port to Python-3 has happened only in 7.8.0+. Hence, it is a kind of workaround which will fade out over time. This just for the explanation.

**Comment by smathermather** [comment]
> Older version will still use python(-2) since the port to Python-3 has happened only in 7.8.0+. Hence, it is a kind of workaround which will fade out over time. This just for the explanation.

That makes perfect sense. I wasn't sure where the injection was coming from. That answers my other question, which is whether this needs to retain compatibility with `python2`. I'd take that as a "yes".

Since the changes I made in https://github.com/OSGeo/grass-addons/pull/355 are just warnings under Python3, is the best approach to ignore the warnings for now and simply fix the TypeError in a way that is compatible with both 2 and 3?

**Comment by smathermather** [comment]
Hmm. The core error is over my head (I've never ported from Python2 to 2/3), as simple as it seems:

```
line 313, in main
    proc[i] = grass.mapcalc_start("$cost_n_cleansed =
if($cost_n == 0, 0.1, $cost_n)",
  File "/usr/lib/grass78/etc/python/grass/script/raster.py",
line 163, in mapcalc_start
    p.stdin.write(e)
TypeError: a bytes-like object is required, not 'str'
syntax error
Parse error
```

**Comment by petrasovaa** [comment]
> Hmm. The core error is over my head (I've never ported from Python2 to 2/3), as simple as it seems:
> 
> ```
> line 313, in main
>     proc[i] = grass.mapcalc_start("$cost_n_cleansed =
> if($cost_n == 0, 0.1, $cost_n)",
>   File "/usr/lib/grass78/etc/python/grass/script/raster.py",
> line 163, in mapcalc_start
>     p.stdin.write(e)
> TypeError: a bytes-like object is required, not 'str'
> syntax error
> Parse error
> ```

Hm, this should have been fixed in https://github.com/OSGeo/grass/pull/738 so available in 7.8.4 I think. Maybe you need to update GRASS? Function mapcalc_start should be able to accept string as of 7.8.4.

**Comment by smathermather** [comment]
Ah! Well, serves me right for installing via repo and then complaining about bugs that have been fixed for 6 months. Sorry for the noise: I will close this and the pull request, and thanks for the heads up.

I'll build from source, and if I see any issues I'll re-open.

**Comment by petrasovaa** [comment]
That particular problem was coming from grass, but there are things to be fixed in v.surf.icw addon itself, so #355 is still relevant.

**Comment by smathermather** [comment]
Ok. Pull request re-opened and grass is now building on machine. I am regretting PopOS a little for dependencies. *Le sigh* (it's like the early days of Ubuntu) but building is happening and I'll keep tracking and troubleshooting this.

**Comment by smathermather** [comment]
Per the notes on the pull request, I have run through the 3 steps of `futurize`, manually fixed the tests that result in warnings (issues not addressed by `futurize`) and tested in a python3 environment without incident.
