### ISSUE TITLE
[Bug] check_addons_urls.sh: tput: No value for $TERM and no -T specified error in cronjob

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#359]
Apparently there is no $TERM definition in a cronjob, leading to (see [build.log](https://grass.osgeo.org/grass78/binary/linux/snapshot/build.log))

```
...
Compiling v.vect.stats.multi... SUCCESS
Compiling v.vol.idw... SUCCESS
Compiling v.what.rast.multi... SUCCESS
Compiling v.what.spoly... SUCCESS
Compiling v.what.strds.timestamp... SUCCESS

tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
Checking db.csw.admin.html... source and commits URL: CORRECT
tput: No value for $TERM and no -T specified
Checking db.csw.harvest.html... source and commits URL: CORRECT
tput: No value for $TERM and no -T specified
Checking db.csw.run.html... source and commits URL: CORRECT
tput: No value for $TERM and no -T specified
Checking db.join.html... source and commits URL: CORRECT
...
```

which comes from here:

https://github.com/OSGeo/grass-addons/blob/a050557e5cacc7b2030b9e9c2eef22f4823c85d8/tools/cronjobs_osgeo_lxd/check_addons_urls.sh#L24

https://stackoverflow.com/a/35808520/452464

suggests to defined in the [crontab](https://github.com/OSGeo/grass-addons/blob/master/tools/cronjobs_osgeo_lxd/cron_job_list_grass) this line:

TERM=xterm

Does it make sense?

**Comment by tmszi** [comment]
https://github.com/OSGeo/grass-addons/blob/a050557e5cacc7b2030b9e9c2eef22f4823c85d8/tools/cronjobs_osgeo_lxd/check_addons_urls.sh#L24-L25

These variables change message text color on stdout (terminal) depending on whether the URL address is correct or incorrect.

> Does it make sense?

Yes it does, for quick visual orientation in the log file printed to the stdout (terminal).

**Comment by neteler** [comment]
I have added it in 
https://github.com/OSGeo/grass-addons/commit/aa5b5b799f60981e64accb6b3a574a81e94a15ab

Let's see at the next run of the cronjob.

**Comment by wenzeslaus** [comment]
`TERM=xterm` does make sense to me for a cron job or other non-interactive session. There is no `TERM` because there is no interactive terminal, no?

One way to test that these scripts work correctly is running them with `nohup` and inspecting the output which it should be nice and not contain any strange characters visible with, e.g., plain `less`. (Lessons learned from making `grass.py` run without an interactive terminal. I added tests for tty to check whether interactive terminal commands and a sub-shell should run.)

**Comment by neteler** [comment]
Currently, with the `TERM=xterm` setting the cronjob writes out ESC chars into the https://grass.osgeo.org/grass78/binary/linux/snapshot/build.log file:

```
(B[mChecking db.csw.admin.html... source and commits URL: CORRECT
(B[m(B[mChecking db.csw.harvest.html... source and commits URL: CORRECT
(B[m(B[mChecking db.csw.run.html... source and commits URL: CORRECT
...
```

I don't mind, just reporting.

**Comment by tmszi** [comment]
> Currently, with the `TERM=xterm` setting the cronjob writes out ESC chars into the https://grass.osgeo.org/grass78/binary/linux/snapshot/build.log file:
> 
> ```
> �(B�[mChecking db.csw.admin.html... source and commits URL: CORRECT
> �(B�[m�(B�[mChecking db.csw.harvest.html... source and commits URL: CORRECT
> �(B�[m�(B�[mChecking db.csw.run.html... source and commits URL: CORRECT
> ...
> ```
> 
> I don't mind, just reporting.

I think it will be better if the color text output is optional [PR](https://github.com/OSGeo/grass-addons/pull/366).
