### ISSUE TITLE
v.what.strds.timestamp: v.what.rast runs twice

### ISSUE THREAD

**Issue by pesekon2** [OSGeo/grass-addons#391]
**Name of the addon**

v.what.strds.timestamp

**Describe the bug**

At [these lines](https://github.com/OSGeo/grass-addons/blob/master/grass7/vector/v.what.strds.timestamp/v.what.strds.timestamp.py#L127-L131), the `v.what.rast` module actually runs twice. Firstly without the `i` flag (`Module()`), later with the `i` flag (`run()`). As this is probably the most time-expensive part of the module, it is making it twice as slow.

**Comment by ninsbl** [comment]
Fixed in #392
