### ISSUE TITLE
i.sentinel.download pandas dependency

### ISSUE THREAD

**Issue by lucadelu** [OSGeo/grass-addons#411]
Is `pandas` library really required by i.sentinel.download?
It seems just imported but not used in all i.sentinel.download.py file

**Comment by neteler** [comment]
If not yet, it will be needed... see this PR #419 

https://github.com/OSGeo/grass-addons/pull/419/files#diff-8f46003ae8b0dbe657ce69e1ef7305b221abb83834dfef76ede48c24f04cc315R562
