### ISSUE TITLE
[Bug] r.fill.gaps addon missing

### ISSUE THREAD

**Issue by dnewcomb** [OSGeo/grass-addons#418]
**Name of the addon**
r.fill.gaps

**Describe the bug**

missing in addons repository with latest update to GRASS 7.8.5 on ubuntugis for Ubuntu 20.04 .  With latest update, g.extension.all -f was required to reload extensions.  
------------------------------------------------------------
Reinstalling extension <r.fill.gaps>...
------------------------------------------------------------
WARNING: Extension <r.fill.gaps> already installed. Re-installing...
Fetching <r.fill.gaps> from GRASS GIS Addons repository (be patient)...
svn: E170000: URL 'https://github.com/OSGeo/grass-addons/trunk/grass7/raster/r.fill.gaps' doesn't exist
ERROR: GRASS Addons <r.fill.gaps> not found
ERROR: Unable to process extension:r.fill.gaps

**To Reproduce**
From the command line run:
g.extension extension=r.fill.gaps

**Expected behavior**
Reinstalling extension <r.fill.gaps>...
------------------------------------------------------------
WARNING: Extension <r.fill.gaps> already installed. Re-installing...
Fetching <r.fill.gaps> from GRASS GIS Addons repository (be patient)...
Compiling...
Installing...
Updating extensions metadata file...
Updating extension modules metadata file...
Installation of <r.fill.gaps> successfully finished

**Screenshots**

**System description (please complete the following information):**
 - Operating System: Linux Ubuntu 20.04 with Ubuntugis-unstable
 - GRASS GIS version 7.8.5

**Additional context**
g.extension is looking forr.fill.gaps in https://github.com/OSGeo/grass-addons/trunk/grass7/raster, but there is no such directory.
There is no trunk directory, there is only a https://github.com/OSGeo/grass-addons/tree/master/grass7/raster subdirectory

Looking in https://github.com/OSGeo/grass-addons/tree/master/grass7/raster, I notice that there is no r.fill.gaps. 

g.extension is looking for r.fill.gaps in a directory that no longer exists, r.fill.gaps does not exist in the directory that does exist.

The other extensions in the installation updated normally.

**Comment by petrasovaa** [comment]
r.fill.gaps was recently removed, because it has been in GRASS core for some time now under different name r.fill.stats.

**Comment by neteler** [comment]
This has happened in "addons: remove deprecated addons #375".
I'll write an announcement in the mailing list.

**Comment by dnewcomb** [comment]
Thank you! Sorry to have missed the change.
