### ISSUE TITLE
[Bug] i.landsat8.qc: clouds not identified

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-addons#441]
`i.landsat8.qc` seems to not identify clouds and only sees a very thin line of cloud shadows. Meanwhile, if I display the QA bands, both clouds and shadows are identifiable. Is something wrong (or anything might have changed) with the respective bits in the QA band? @ninsbl any ideas??

**To Reproduce**
```
g.extension extension=i.landsat
g.extension extension=i.landsat8.qc

i.landsat.download settings=USGS_SETTING.txt \
  id=LC82290822020014LGN00 \
  output=$HOME/landsat_data

i.landsat.import -r \
  input=$HOME/gisdata/landsat_data \
  extent=region

# create a rule set
i.landsat8.qc cloud="Maybe,Yes" \
  cloud="Maybe,Yes" \
  output=Cloud_Mask_rules.txt

# reclass the BQA band based on the rule set created
r.reclass input=LC08_L1TP_229082_20200114_20200127_01_T1_BQA \
  output=LC08_229082_20200114_Cloud_Mask \
  rules=Cloud_Mask_rules.txt

# display reclassified map
d.mon wx0
d.rast LC08_229082_20200114_Cloud_Mask      # all yellow

# create a rule set
i.landsat8.qc cloud="Maybe,Yes" \
  cloud_shadow="Maybe,Yes" \
  output=Cloud_Mask_rules.txt

# reclass the BQA band based on the rule set created
r.reclass input=LC08_L1TP_229082_20200114_20200127_01_T1_BQA \
  output=LC08_229082_20200114_Cloud_Mask \
  rules=Cloud_Mask_rules.txt

# display reclassified map
d.mon wx0
d.rast LC08_229082_20200114_Cloud_Mask      # only a small thin line is recognized
```

**Expected behavior**
That clouds and their shadows are properly identified as visible in the QA band

**Screenshots**
![image](https://user-images.githubusercontent.com/20075188/108711227-5245c800-7515-11eb-9007-28697f919c2f.png) ![image](https://user-images.githubusercontent.com/20075188/108711274-638ed480-7515-11eb-9d40-132ddda1f515.png)
![image](https://user-images.githubusercontent.com/20075188/108711340-81f4d000-7515-11eb-8e80-3dc90d87b81e.png)
![image](https://user-images.githubusercontent.com/20075188/108711829-32fb6a80-7516-11eb-96fc-1b91620465c9.png)

**System description (please complete the following information):**
 - Operating System: Linux - Fedora 33
 - GRASS GIS version 7.8.5

**Additional context**
I only imported a subset of the full scene, but that was not a problem earlier. This is the region setting:
```
g.region -p
projection: 99 (POSGAR 2007 / Argentina 4)
zone:       0
datum:      towgs84=-0.41,0.46,-0.35,0,0,0,0
ellipsoid:  grs80
north:      6536310
south:      6512040
west:       4375290
east:       4399560
nsres:      30
ewres:      30
rows:       809
cols:       809
cells:      654481
```

**Comment by veroandreo** [comment]
Here the file with rules after `i.landsat8.qc cloud="Maybe,Yes" output=Cloud_Mask_rules.txt`
[Cloud_Mask_rules.txt](https://github.com/OSGeo/grass-addons/files/6022159/Cloud_Mask_rules.txt)

and here the one after `i.landsat8.qc cloud_shadow="Maybe,Yes" output=Cloud_Mask_rules.txt`:
[Cloud_Mask_rules.txt](https://github.com/OSGeo/grass-addons/files/6022180/Cloud_Mask_rules.txt)

Indeed, I believe there's something odd with the bits...

**Comment by ninsbl** [comment]
Maybe a python 2 / 3 issue, maybe changres in the QA bands?

Here is the latest documentation:
https://www.usgs.gov/core-science-systems/nli/landsat/landsat-collection-2-quality-assessment-bands

Probably worth rewriting/adjusting the module to also handle landsat 4-7 and aeorosl QA bands?

**Comment by veroandreo** [comment]
There's definitely a mismatch between i.landsat8.qc and the latest docs regarding bits. Which Landsat collection was i.landsat8.qc implemented for?

`i.landsat` downloads collection 1 (because landsatxplore still uses only collection 1 - this should change soon according to https://github.com/yannforget/landsatxplore/issues/29#issuecomment-779691808). Maybe this should also be considered in the module besides adapting them to handle landsat 4-7 and aeorosl QA bands, if indeed it changes from one collection to the other and among levels within collections.

Now, any ideas on how to solve this at least for my course starting in 2 weeks? Shall I just manually/interactively check the values in QA band shown above and mask them?

**Comment by ninsbl** [comment]
The documentation at usgs that the module is based on is no longer available, unfortunately. Do you know where to find documentation for qa files i.landsat receives? Should be doable to fix this before your course...

**Comment by ninsbl** [comment]
Is that the relevant documentation:
https://www.usgs.gov/core-science-systems/nli/landsat/landsat-collection-1-level-1-quality-assessment-band?qt-science_support_page_related_con=0#qt-science_support_page_related_con
?

**Comment by veroandreo** [comment]
> The documentation at usgs that the module is based on is no longer available, unfortunately. Do you know where to find documentation for qa files i.landsat receives? Should be doable to fix this before your course...

This is what I found for Collection 1 level 1: 
- https://www.usgs.gov/core-science-systems/nli/landsat/landsat-collection-1?qt-science_support_page_related_con=1#qt-science_support_page_related_con
- https://www.usgs.gov/core-science-systems/nli/landsat/landsat-collection-1-level-1-quality-assessment-band?qt-science_support_page_related_con=0#qt-science_support_page_related_con
- only L8: https://prd-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/atoms/files/LSDS-809-Landsat8-Level1DFCB-v11.pdf

**Comment by ninsbl** [comment]
Maybe we should deprecate / remove this module now that #442 is merged?

**Comment by ninsbl** [comment]
Replaced by https://github.com/OSGeo/grass-addons/tree/master/grass7/imagery/i.landsat/i.landsat.qa

**Comment by NikosAlexandris** [comment]
Just a link to some old work: https://gitlab.com/NikosAlexandris/i.landsat8.qa/-/blob/d073f625cd2114e80a681590fe46f4d9f6040a8a/i.landsat8.qa.py
