### ISSUE TITLE
r.basin - ERROR: Column <perimeter> exists

### ISSUE THREAD

**Issue by IreneM21** [OSGeo/grass-addons#443]
I'm having troubles running r.basin. 
I kept getting the same error message so I've tried to run it using the North Carolina dataset by writing: (as the example from r.basin documentation suggests)

g.region raster=elevation -p
r.basin map=elevation prefix=my_basin coord=637304.924954,218617.100523 dir=/tmp/my_basin threshold=1000

The error message is:
ERROR: Column perimeter exists. To overwrite, use the --overwrite flag

How can I solve this issue?

**Comment by hellik** [comment]
>The error message is:
>ERROR: Column perimeter exists. To overwrite, use the --overwrite flag

it's not a bug, though a  behaviour change in an underlying used module.

**Comment by hellik** [comment]
[v.to.db manual](https://grass.osgeo.org/grass78/manuals/v.to.db.html)

```
If the column exists, the --overwrite flag is required to overwrite it. 
```

so, the v.to.db calls in the script should use the overwrite flag

**Comment by hellik** [comment]
> so, the v.to.db calls in the script should use the overwrite flag

the overwrite flag in GRASS python works, e.g.

```

    grass.run_command("v.to.db", map = v_habitat,
                                     option = 'area',
                                     layer = 1,
                                     columns = 'habarea',
                                     overwrite = True)
```

**Comment by hellik** [comment]
tested here locally; 

just add to every **grass.run_command('v.to.db' ...**  command the overwrite flag **overwrite = True**  for a quick workaround.

the script will need a fix to adapt to the new v.to.db behaviour. @madi

**Comment by IreneM21** [comment]
If I add the flag --overwrite to the r.basin function (I use the console in GRASS 7.8) I get this other error message:
<img width="773" alt="Schermata 2021-02-24 alle 10 03 56" src="https://user-images.githubusercontent.com/79516371/108976406-c3a58800-7687-11eb-9eef-143f29a10717.png">

I have not used that flag before because in the known problems of the function it says that "r.basin does not handle overwriting. You must manually delete the output products already created (maps, text files, figures) before running it again "

**Comment by hellik** [comment]
Which operating system are you using? 

See also the manual: a working matplotlib is needed. 

I didn't mean the overwrite flag of r.basin. 

Open the script in an text editor and add as stated in my previous comment  overwrite = True to every v.to.db call in the script.

**Comment by IreneM21** [comment]
I'm using macOS. 
Also, do I have to install Matplotlib onto the IDLE or using the command line?
Thank you so much for your help, I'll definitely try to edit the script.

**Comment by hellik** [comment]
>I'm using macOS.
>Also, do I have to install Matplotlib onto the IDLE or using >the command line?

I'm no mac user. 

Maybe @nilason  any idea?

**Comment by nilason** [comment]
You can check the availability of matplotlib in python console:
```
import matplotlib; matplotlib.__version__
```

version 3.3.3 is included with the binary distribution.

**Comment by nilason** [comment]
Now I also tested with official binary with a "clean slate":

```
g.region raster=elevation@PERMANENT -p
r.basin map=elevation@PERMANENT prefix=my_basin coord=637304.924954,218617.100523 dir=/Users/Shared threshold=1000
SECTION 1 beginning: Initiating Variables. 4 sections total.
SECTION 1a: Mark masked and NULL cells
 100%
SECTION 1b: Determining Offmap Flow.
 100%
SECTION 2: A* Search.
 100%
SECTION 3a: Accumulating Surface Flow with MFD.
 100%
SECTION 3b: Adjusting drainage directions.
SECTION 4: Closing Maps.
Closing accumulation map
Writing out only positive flow accumulation values.
Cells with a likely underestimate for flow accumulation can no longer be
identified.
 100%
Closing flow direction map
Loading input raster maps...
 100%
Initializing A* search...
 100%
A* Search...
 100%
Extracting streams...
 100%
Thinning stream segments...
 100%
Writing output raster maps...
 100%
Scanning input for column types...
Number of columns: 3
Number of rows: 1
Importing points...
 100%
Populating table...
Building topology for vector map <my_basin_elevation_outlet@user1>...
Registering primitives...
Reading raster map <my_basin_elevation_stream_e>...
 100%
Building topology for vector map <my_basin_elevation_outlet_snap@user1>...
Registering primitives...
Reading features...
 100%
Writing raster map...
 100%
v.to.rast complete.
Memory swap calculation (may take some time)...
Reading raster map <my_basin_elevation_drainage_e>...
 100%
Calculating basins using vector point map...
Delineating basins for 1 outlets...
 100%
Writing raster map <my_basin_elevation_basin>...
 100%
Delineation of basin done
 100%
 100%
Rename raster <tmp> to <my_basin_elevation_accumulation>
 100%
Rename raster <tmp> to <my_basin_elevation_drainage>
 100%
 100%
Rename raster <tmp> to <my_basin_elevation_drainage_e>
 100%
Rename raster <tmp> to <my_basin_elevation_stream_e>
Raster map <my_basin_elevation_stream_e> - 1350 rows X 1500 columns
Bounding box: l = 320, r = 732, t = 605, b = 1006
Pass number 1
Deleted 6 pixels
Pass number 2
Deleted 0 pixels
Thinning completed successfully.
Output map 1350 rows X 1500 columns
Window 1350 rows X 1500 columns
Extracting lines...
 100%
 100%
Building topology for vector map <my_basin_elevation_network@user1>...
Registering primitives...
r.to.vect complete.
 100%
Aspect raster map <my_basin_elevation_aspect> complete
Slope raster map <my_basin_elevation_slope> complete
Extracting areas...
 100%
Writing areas...
 100%
Updating attributes...
 100%
Building topology for vector map <my_basin_elevation_basin@user1>...
Registering primitives...
Building areas...
 100%
Attaching islands...
 100%
Attaching centroids...
 100%
r.to.vect complete.
ERROR: Column <perimeter> exists. To overwrite, use the --overwrite flag

------------------------------

An ERROR occurred running r.basin
Please check for error messages above or try with another pairs of outlet
coordinates
Removing region definition <original>
```

Files that may need to be removed after failure:
```
g.remove type=all pattern=my_basin_*
g.remove -f type=raster name=r_elevation_crop
g.remove -f type=region name=original
```

**Comment by hellik** [comment]
> Now I also tested with official binary with a "clean slate":
> 
> ```
> g.region raster=elevation@PERMANENT -p
> r.basin map=elevation@PERMANENT prefix=my_basin coord=637304.924954,218617.100523 dir=/Users/Shared threshold=1000
> SECTION 1 beginning: Initiating Variables. 4 sections total.
> SECTION 1a: Mark masked and NULL cells
>  100%
> SECTION 1b: Determining Offmap Flow.
>  100%
> SECTION 2: A* Search.
>  100%
> SECTION 3a: Accumulating Surface Flow with MFD.
>  100%
> SECTION 3b: Adjusting drainage directions.
> SECTION 4: Closing Maps.
> Closing accumulation map
> Writing out only positive flow accumulation values.
> Cells with a likely underestimate for flow accumulation can no longer be
> identified.
>  100%
> Closing flow direction map
> Loading input raster maps...
>  100%
> Initializing A* search...
>  100%
> A* Search...
>  100%
> Extracting streams...
>  100%
> Thinning stream segments...
>  100%
> Writing output raster maps...
>  100%
> Scanning input for column types...
> Number of columns: 3
> Number of rows: 1
> Importing points...
>  100%
> Populating table...
> Building topology for vector map <my_basin_elevation_outlet@user1>...
> Registering primitives...
> Reading raster map <my_basin_elevation_stream_e>...
>  100%
> Building topology for vector map <my_basin_elevation_outlet_snap@user1>...
> Registering primitives...
> Reading features...
>  100%
> Writing raster map...
>  100%
> v.to.rast complete.
> Memory swap calculation (may take some time)...
> Reading raster map <my_basin_elevation_drainage_e>...
>  100%
> Calculating basins using vector point map...
> Delineating basins for 1 outlets...
>  100%
> Writing raster map <my_basin_elevation_basin>...
>  100%
> Delineation of basin done
>  100%
>  100%
> Rename raster <tmp> to <my_basin_elevation_accumulation>
>  100%
> Rename raster <tmp> to <my_basin_elevation_drainage>
>  100%
>  100%
> Rename raster <tmp> to <my_basin_elevation_drainage_e>
>  100%
> Rename raster <tmp> to <my_basin_elevation_stream_e>
> Raster map <my_basin_elevation_stream_e> - 1350 rows X 1500 columns
> Bounding box: l = 320, r = 732, t = 605, b = 1006
> Pass number 1
> Deleted 6 pixels
> Pass number 2
> Deleted 0 pixels
> Thinning completed successfully.
> Output map 1350 rows X 1500 columns
> Window 1350 rows X 1500 columns
> Extracting lines...
>  100%
>  100%
> Building topology for vector map <my_basin_elevation_network@user1>...
> Registering primitives...
> r.to.vect complete.
>  100%
> Aspect raster map <my_basin_elevation_aspect> complete
> Slope raster map <my_basin_elevation_slope> complete
> Extracting areas...
>  100%
> Writing areas...
>  100%
> Updating attributes...
>  100%
> Building topology for vector map <my_basin_elevation_basin@user1>...
> Registering primitives...
> Building areas...
>  100%
> Attaching islands...
>  100%
> Attaching centroids...
>  100%
> r.to.vect complete.
> ERROR: Column <perimeter> exists. To overwrite, use the --overwrite flag
> 
> ------------------------------
> 
> An ERROR occurred running r.basin
> Please check for error messages above or try with another pairs of outlet
> coordinates
> Removing region definition <original>
> ```
> 
> Files that may need to be removed after failure:
> 
> ```
> g.remove type=all pattern=my_basin_*
> g.remove -f type=raster name=r_elevation_crop
> g.remove -f type=region name=original
> ```

Thanks for testing 

>ERROR: Column <perimeter> exists.

Hopefully I find time today to fix the script for this one (remove add coloumns before the v.to.db calls in the script); it's a behavior change in v.to.db after r.basin has been written. 

Still open if the matplotlib engine which is choosen in the script is working in mac

**Comment by nilason** [comment]
Would be good to add prefix to `r_elevation_crop` and the `original` region too.

**Comment by IreneM21** [comment]
> > Now I also tested with official binary with a "clean slate":
> > ```
> > g.region raster=elevation@PERMANENT -p
> > r.basin map=elevation@PERMANENT prefix=my_basin coord=637304.924954,218617.100523 dir=/Users/Shared threshold=1000
> > SECTION 1 beginning: Initiating Variables. 4 sections total.
> > SECTION 1a: Mark masked and NULL cells
> >  100%
> > SECTION 1b: Determining Offmap Flow.
> >  100%
> > SECTION 2: A* Search.
> >  100%
> > SECTION 3a: Accumulating Surface Flow with MFD.
> >  100%
> > SECTION 3b: Adjusting drainage directions.
> > SECTION 4: Closing Maps.
> > Closing accumulation map
> > Writing out only positive flow accumulation values.
> > Cells with a likely underestimate for flow accumulation can no longer be
> > identified.
> >  100%
> > Closing flow direction map
> > Loading input raster maps...
> >  100%
> > Initializing A* search...
> >  100%
> > A* Search...
> >  100%
> > Extracting streams...
> >  100%
> > Thinning stream segments...
> >  100%
> > Writing output raster maps...
> >  100%
> > Scanning input for column types...
> > Number of columns: 3
> > Number of rows: 1
> > Importing points...
> >  100%
> > Populating table...
> > Building topology for vector map <my_basin_elevation_outlet@user1>...
> > Registering primitives...
> > Reading raster map <my_basin_elevation_stream_e>...
> >  100%
> > Building topology for vector map <my_basin_elevation_outlet_snap@user1>...
> > Registering primitives...
> > Reading features...
> >  100%
> > Writing raster map...
> >  100%
> > v.to.rast complete.
> > Memory swap calculation (may take some time)...
> > Reading raster map <my_basin_elevation_drainage_e>...
> >  100%
> > Calculating basins using vector point map...
> > Delineating basins for 1 outlets...
> >  100%
> > Writing raster map <my_basin_elevation_basin>...
> >  100%
> > Delineation of basin done
> >  100%
> >  100%
> > Rename raster <tmp> to <my_basin_elevation_accumulation>
> >  100%
> > Rename raster <tmp> to <my_basin_elevation_drainage>
> >  100%
> >  100%
> > Rename raster <tmp> to <my_basin_elevation_drainage_e>
> >  100%
> > Rename raster <tmp> to <my_basin_elevation_stream_e>
> > Raster map <my_basin_elevation_stream_e> - 1350 rows X 1500 columns
> > Bounding box: l = 320, r = 732, t = 605, b = 1006
> > Pass number 1
> > Deleted 6 pixels
> > Pass number 2
> > Deleted 0 pixels
> > Thinning completed successfully.
> > Output map 1350 rows X 1500 columns
> > Window 1350 rows X 1500 columns
> > Extracting lines...
> >  100%
> >  100%
> > Building topology for vector map <my_basin_elevation_network@user1>...
> > Registering primitives...
> > r.to.vect complete.
> >  100%
> > Aspect raster map <my_basin_elevation_aspect> complete
> > Slope raster map <my_basin_elevation_slope> complete
> > Extracting areas...
> >  100%
> > Writing areas...
> >  100%
> > Updating attributes...
> >  100%
> > Building topology for vector map <my_basin_elevation_basin@user1>...
> > Registering primitives...
> > Building areas...
> >  100%
> > Attaching islands...
> >  100%
> > Attaching centroids...
> >  100%
> > r.to.vect complete.
> > ERROR: Column <perimeter> exists. To overwrite, use the --overwrite flag
> > 
> > ------------------------------
> > 
> > An ERROR occurred running r.basin
> > Please check for error messages above or try with another pairs of outlet
> > coordinates
> > Removing region definition <original>
> > ```
> > 
> > 
> > Files that may need to be removed after failure:
> > ```
> > g.remove type=all pattern=my_basin_*
> > g.remove -f type=raster name=r_elevation_crop
> > g.remove -f type=region name=original
> > ```
> 
> Thanks for testing
> 
> > ERROR: Column  exists.
> 
> Hopefully I find time today to fix the script for this one (remove add coloumns before the v.to.db calls in the script); it's a behavior change in v.to.db after r.basin has been written.
> 
> Still open if the matplotlib engine which is choosen in the script is working in mac

Thank you for you help. It would be great if you could edit the script!

**Comment by hellik** [comment]
r.basin updated now in upstream git repository.

@IreneM21  please try by installing again via g.extension

**Comment by IreneM21** [comment]
Thank you for your help! I'll try on Monday and I'll let you know if it worked

**Comment by nilason** [comment]
I was afraid this would be a double bug. The fix @hellik made regarding the overwrite problem works.

But there is an issue remaining with the binary distribution of the Mac version. I will look into a permanent solution for this, however I can offer a workaround for the time being:

change the first line `#!/usr/bin/env python3` or `#!/usr/bin/env python`
to  `#!/usr/bin/env python.app`

for the following files:

```
~/Library/GRASS/7.8/Modules/scripts/r.basin
~/Library/GRASS/7.8/Modules/scripts/r.hypso
~/Library/GRASS/7.8/Modules/scripts/r.width.funct
```

**Comment by nilason** [comment]
The Python related, Mac binary specific issue is reported with https://github.com/OSGeo/grass/issues/1414.

**Comment by nilason** [comment]
@IreneM21 If things work out as expected with r.basin now, feel free to close this issue.

**Comment by IreneM21** [comment]
Everything works fine now, thank you everyone for your help and support!
