### ISSUE TITLE
[Bug] i.sentinel.mask does not work for S2 level 2A data 

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-addons#446]
i.sentinel.mask does not work for level 2A data, even when providing the `scale_fac`. It seems to still expect a DCELL of FCELL raster map. I thought [this change](5c8f1da73e7590187d0fc32119217600487ba672) had addressed that.

**To Reproduce**
```
i.sentinel.download \
  settings=SENTINEL_SETTING.txt \
  uuid=9a1ea49c-0561-4aa5-ba7a-dc820dc1a316 \
  output=/tmp
i.sentinel.import -rc \
  input=/tmp \
  pattern='B(02_1|03_1|04_1|08_1|8A_2|11_2|12_2)0m' \
  extent=region
i.sentinel.mask \
  blue=T20JLL_20200330T141049_B02_10m \
  green=T20JLL_20200330T141049_B03_10m \
  red=T20JLL_20200330T141049_B04_10m \
  nir=T20JLL_20200330T141049_B08_10m \
  nir8a=T20JLL_20200330T141049_B8A_20m \
  swir11=T20JLL_20200330T141049_B11_20m \
  swir12=T20JLL_20200330T141049_B12_20m \
  cloud_mask=cloud \
  shadow_mask=shadow \
  scale_fac=10000 \
  mtd=/tmp/S2B_MSIL2A_20200330T141049_N0214_R110_T20JLL_20200330T182252.SAFE/GRANULE/L2A_T20JLL_A016009_20200330T141532/MTD_TL.xml
```

This is what I get (btw, I re-installed i.sentinel this morning):
```
WARNING: All subsequent operations will be limited to the current
         computational region
WARNING: No rescale factor has been applied
ERROR: Raster maps must be DCELL o FCELL
```

Am I doing something wrong here @RobiFag @anikaweinmann ? or missunderstanding it? I really appreciate any help

**System description:**
 - Operating System: Linux - Fedora 33
 - GRASS GIS version 7.8.5

**Additional context:**

This is the region setting
```
g.region -p
projection: 99 (POSGAR 2007 / Argentina 4)
zone:       0
datum:      towgs84=-0.41,0.46,-0.35,0,0,0,0
ellipsoid:  grs80
north:      6536310
south:      6512040
west:       4375300
east:       4399580
nsres:      10
ewres:      10
rows:       2427
cols:       2428
cells:      5892756
```

and the scene has both clouds and cloud shadows: 

![image](https://user-images.githubusercontent.com/20075188/108862391-775b3900-75f0-11eb-9587-ebe6b8e16a55.png)

**Comment by veroandreo** [comment]
Forgot the -s flag!!! :facepalm: Sorry for the noise! Closing...

**Comment by neteler** [comment]
> Forgot the -s flag!!! facepalm Sorry for the noise! Closing...

Anything to be improved in error messages or manual?

**Comment by veroandreo** [comment]
> > Forgot the -s flag!!! facepalm Sorry for the noise! Closing...
> 
> Anything to be improved in error messages or manual?

no... the use of -s is explained... It was me missing it
