### ISSUE TITLE
Process of compiling Add-Ons on the Windows platform has stopped 

### ISSUE THREAD

**Issue by tmszi** [OSGeo/grass-addons#469]
**Describe the bug**
It looks like the process of compiling Add-Ons on the Windows platform has stopped to date [Tue, 26 Jan 2021 02:10:14](https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/latest/logs/).

**Expected behavior**
Regular compilation of Add-Ons.

**Comment by neteler** [comment]
Is there a chance to move it to GitHub, @landam? I don't remember if @HuidaeCho tried that already...

**Comment by petrasovaa** [comment]
They seem to be compiling just fine:
https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/latest/

Not sure where the date in the log comes from.
But of course moving to github would be nice.

**Comment by HuidaeCho** [comment]
> Is there a chance to move it to GitHub, @landam? I don't remember if @HuidaeCho tried that already...

I haven't tried compiling addons on github. Since it's a separate repo, it'll take even longer than the core because the core has to be compiled first. Or.. maybe, I could download an artifact from the core to save time? I still need to figure out how to release artifacts properly. #1212

**Comment by hellik** [comment]
> > Is there a chance to move it to GitHub, @landam? I don't remember if @HuidaeCho tried that already...
> 
> I haven't tried compiling addons on github. Since it's a separate repo, it'll take even longer than the core because the core has to be compiled first. Or.. maybe, I could download an artifact from the core to save time? I still need to figure out how to release artifacts properly. [OSGeo/grass#1212](https://github.com/OSGeo/grass/pull/1212)

@HuidaeCho  fyi: in the OSGeo4W next generation, no administrator rights for installation are  needed anymore

**Comment by HuidaeCho** [comment]
> > > Is there a chance to move it to GitHub, @landam? I don't remember if @HuidaeCho tried that already...
> > 
> > 
> > I haven't tried compiling addons on github. Since it's a separate repo, it'll take even longer than the core because the core has to be compiled first. Or.. maybe, I could download an artifact from the core to save time? I still need to figure out how to release artifacts properly. [OSGeo/grass#1212](https://github.com/OSGeo/grass/pull/1212)
> 
> @HuidaeCho fyi: in the OSGeo4W next generation, no administrator rights for installation are needed anymore

That's a great long-awaited move! Thanks for letting me know.

**Comment by wenzeslaus** [comment]
> Since it's a separate repo, it'll take even longer than the core because the core has to be compiled first.

I don't think time is an issue here, at least not initially. However, you could also download daily build and/or latest release from https://grass.osgeo.org/download/windows/ or use OSGeo4W. Same for macOS. On Linux, it is just so easy (and fast) that there is not many reasons not compile it, but also testing with, let's say, UbuntuGIS PPA would make sense if we would like to ensure that the addons work with it.
