### ISSUE TITLE
[Bug] Add Python GDAL bindings needed by v.in.pygbif to CI

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass-addons#472]
**Name of the addon**

v.in.pygbif

**Describe the bug**

GitHub Actions configuration misses GDAL Python bindings and thus v.in.pygbif fails.

```
Traceback (most recent call last):
  File "vector/v.in.pygbif/testsuite/test_pygbif_import.py", line 35, in test_poa_taxon_match
    self.assertModule(v_in_pygbif_match)
  File "etc/python/grass/gunittest/case.py", line 1419, in assertModule
    self.fail(self._formatMessage(msg, stdmsg))
AssertionError: Running <v.in.pygbif> module ended with non-zero return code (1)
Called: v.in_pygbif(output='gbif_poa1', taxa='Poa', basisofrecord='ALL', rank='species', flags='g', verbose=True)
See the following errors:
ERROR: Unable to load GDAL Python bindings (requires package 'python-gdal' or Python library GDAL to be installed).
```

**To Reproduce**

Explore e.g.: https://github.com/OSGeo/grass-addons/runs/2048721725 or any other recent run.

**Expected behavior**
Addons repo CI build environment in GitHub Actions (which is running tests) has all the (reasonable) dependencies.

**System description (please complete the following information):**

GitHub Actions Ubuntu 20.04 virtual machine.

**Additional context**
See also eccea34c4d268254498f09c12a8ea85ab668977a.

**Comment by ninsbl** [comment]
Seems fixed in #488
