### ISSUE TITLE
r.learn.ml2: pandas import bug [Bug] 

### ISSUE THREAD

**Issue by anikaweinmann** [OSGeo/grass-addons#536]
**r.learn.ml2: r.learn.train**

The changed import of pandas in `r.learn.ml2` (https://github.com/OSGeo/grass-addons/commit/a768cd308895d4f0cc809ad0befa78fe9e9c3101) leads to an error by using `training_points` in `r.learn.train`:
```
Extracting training data
Traceback (most recent call last):
  File "/home/aweinmann/.grass7/addons/scripts/r.learn.train", line 889, in <module>
    main()
  File "/home/aweinmann/.grass7/addons/scripts/r.learn.train", line 593, in main
    X, y, cat = stack.extract_points(training_points, field)
  File "/home/aweinmann/.grass7/addons/etc/r.learn.ml2/rlearnlib/raster.py", line 902, in extract_points
    df = pd.read_sql_query(
NameError: name 'pd' is not defined
```

**To Reproduce**
1. Use nc_spm_08 location
2. Execute:
```
g.extension r.learn.ml2
g.region raster=landclass96 -p
r.random input=landclass96 npoints=1000 vector=training_points
r.learn.train group=lsat7_2000@landsat training_points=training_points field=value model_name=RandomForestClassifier n_estimators=500 save_model=rf_model.gz
```
3. See error

**Expected behavior**
I expect that t.learn.train runs successfully as it does before the change.

**System description (please complete the following information):**
 - Operating System: Linux Mint 20.1 (Ulyssa)
 - GRASS GIS version 7.8.6
 ```
 g.version -rge
version=7.8.6dev
date=2021
revision=899abdc62
build_date=2021-05-18
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=9aa325a6b
libgis_date=2021-03-26T12:53:51+00:00
proj=6.3.1
gdal=3.0.4
geos=3.8.0
sqlite=3.31.1
 ```

**Comment by stevenpawley** [comment]
Sorry, I introduced this error because I think r.learn.ml2 was not building on windows due to pandas not being imported lazily. I haven't had time to test it properly, but bf698a0e did fix your issue.
