### ISSUE TITLE
[Bug] Source code links in the manual are broken?

### ISSUE THREAD

**Issue by HuidaeCho** [OSGeo/grass-addons#546]
**Name of the addon**
Any modules.

**Describe the bug**
Click the source code link at the bottom of the manual and I get, for example, this link: https://github.com/OSGeo/grass/tree/master/-addons/grass7/general/g.proj.all

It should be https://github.com/OSGeo/grass-addons/tree/master/grass7/general/g.proj.all

**To Reproduce**
1. Open any addon manual
2. Click on the source code at the bottom
3. See error

**Expected behavior**
Open the correct GitHub link.

**Screenshots**

**System description (please complete the following information):**
 - Operating System: [e.g. Windows, Linux, ... incl. version]
 - GRASS GIS version [e.g. 7.8.1]

**Additional context**

**Comment by HuidaeCho** [comment]
Interestingly, https://grass.osgeo.org/grass78/manuals/addons/g.proj.all.html has the correct link. Is it my build, but where and why?

**Comment by neteler** [comment]
> Click the source code link at the bottom of the manual 

... where precisely?

These therein look all fine:
https://grass.osgeo.org/grass7/manuals/addons/

> and I get, for example, this link: https://github.com/OSGeo/grass/tree/master/-addons/grass7/general/g.proj.all

It is lacking the `grass` of `../grass-addons`. However, I am not sure if you try to locally compile the addons?

**Comment by HuidaeCho** [comment]
Here: Available at: g.proj.all source code (history)

I think it's just my build. Where do we generate these links?

**Comment by neteler** [comment]
The link creation happens in core - `utils/mkhtml.py`:

https://github.com/OSGeo/grass/blob/69b2fe5fb0dd10f57c880ee93f34c045d38d3b02/utils/mkhtml.py#L115

**Comment by HuidaeCho** [comment]
Fixed in https://github.com/OSGeo/grass/pull/1645

* Core path: `/home/user/usr/grass/grass`
* Addon path: `/home/user/usr/grass/grass-addons`

Addon path starts with core path, but that doesn't mean I'm inside the core.
