### ISSUE TITLE
Use of pyproj: 'is_latlong()' is deprecated. Please use 'crs.is_geographic'

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#565]
In usage, I get this warning
```
UserWarning: 'is_latlong()' is deprecated. Please use 'crs.is_geographic'.
  warnings.warn("'is_latlong()' is deprecated. Please use 'crs.is_geographic'.")
```

Moreover` pyproj>2.2 `has no `is_latlong()`.

_Originally posted by @LorenzoBottaccioli in https://github.com/OSGeo/grass-addons/issues/537#issuecomment-867508413_

The function is used in some places:

```
grass7/raster/r.denoise/r.denoise.py
118:            if out_proj.is_latlong() == False:

grass7/raster/r.connectivity/r.connectivity.distance/r.connectivity.distance.py
305:    if grass.locn_is_latlong():

grass7/raster/r.in.usgs/r.in.usgs.py
394:        if gscript.locn_is_latlong():

grass7/vector/v.in.geopaparazzi/v.in.geopaparazzi.py
169:    if grass.locn_is_latlong():

grass7/vector/v.what.spoly/v.what.spoly.py
105:    if grass.locn_is_latlong():
```

**Comment by ninsbl** [comment]
I dont think the GRASS function: locn_is_latlong() is affected. See the function definition here:
https://grass.osgeo.org/grass79/manuals/libpython/_modules/script/core.html#locn_is_latlong
For the pyproj API I just created a PR...

**Comment by ninsbl** [comment]
@LorenzoBottaccioli could you please check out the PR mentioned above (#799)?
