### ISSUE TITLE
[Bug] Some AddOns broken for GRASS 8 due to their API change

### ISSUE THREAD

**Issue by pesekon2** [OSGeo/grass-addons#616]
After the branch for GRASS 8 will be finally created (see #528), fix addons affected by this change. 

The PR will tag original authors of the addons as reviewers to give them a chance to state their opinion about changes.

So far those addons were discovered to need some care:

- [x] i.sentinel.coverage - caused by a change in v.db.select
- [x] v.habitat.dem - caused by a change in v.db.select
- [x] r.valley.bottom (temporarily fixed by an if statement) - going to have a PR for `grass7` and `grass8` branch - caused by a change in r.neighbors

**Comment by wenzeslaus** [comment]
Finally, the grass8 now exists and it is the default branch in the grass-addons repo.

**Comment by veroandreo** [comment]
> Finally, the grass8 now exists and it is the default branch in the grass-addons repo.

This means that installing addons for UNIX like systems is again broken in grass 7x, right?

**Comment by wenzeslaus** [comment]
> This means that installing addons for UNIX like systems is again broken in grass 7x, right?

`g.extension r.sun.hourly` works for me with 7.8.6 and with the main branch (v8.2dev). Is there some issue you see now?

> Couldn't we have waited to make it default until we actually release grass 8, to avoid these breakings?

If it doesn't work, the problem is with the code. The new code should always use the appropriate branch, not the default branch.

**Comment by veroandreo** [comment]
> > This means that installing addons for UNIX like systems is again broken in grass 7x, right?
> 
> `g.extension r.sun.hourly` works for me with 7.8.6 and with the main branch (v8.2dev). Is there some issue you see now?
> 
> > Couldn't we have waited to make it default until we actually release grass 8, to avoid these breakings?
> 
> If it doesn't work, the problem is with the code. The new code should always use the appropriate branch, not the default branch.

Apologies for the noise, I asked based on what happened last time. But now I tested and it works just fine. Great! :)

**Comment by wenzeslaus** [comment]
> ...what happened last time...

Yes, last time it happened because Git/GitHub support was not well implemented in g.extension, but when fixing it, @ninsbl worked hard to make it robust for the next change.
