### ISSUE TITLE
g.cloud: update reading of path to GISBASE

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#668]
The current code to retrieve GISBASE may require an update.

_Originally posted by @echoix in https://github.com/OSGeo/grass-addons/issues/667#issuecomment-1008426773_

https://github.com/OSGeo/grass-addons/blob/b595bdb2e67b15f867b3bafe245b90bb6f0ef5e2/src/general/g.cloud/cloud_unpack.py#L47

**Comment by lucadelu** [comment]
Does it make sense to maintain it also for GRASS8 ? 

I think technology evolved and this implementation is outdated.

**Comment by neteler** [comment]
Ok, we may remove it from the `grass8` branch.
