### ISSUE TITLE
[Bug] r.mapcalc.tiled processes option should be renamed

### ISSUE THREAD

**Issue by petrasovaa** [OSGeo/grass-addons#671]
**Name of the addon**
r.mapcalc.tiled

**Describe the bug**
r.mapcalc.tiled uses option `processes` (probably because GridModule uses that in Python API). However other parallelized modules in core use `nprocs` parameter, it is also a new standardized option. 

So my question is should we change it (I would prefer that) or keep it consistent with GridModule? For G8 only maybe? There is a mechanism for backwards compatibility of old option names I believe.

**Comment by neteler** [comment]
Yes, I am +1 to rename it. Backward compatibility can be easily gained through

https://github.com/OSGeo/grass/blob/main/lib/gis/renamed_options
`module_name|oldparam:newparam`

(I suppose that also works for addons)

**Comment by wenzeslaus** [comment]
> There is a mechanism for backwards compatibility of old option names I believe.

Given the placement of the old-new compatibility file, it seems appropriate only for core modules. I guess the idea was that addons don't need backwards compatibility. However, you can always implement it on the addon level. I did that for g.download.location in the grass7 branch.
