### ISSUE TITLE
Roadmap folder: remove from grass8 branch

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#673]
Since we are talking about dropping old code, how is the roadmap folder used, especially in the grass8 branch? Most of it seam to be 13 years old. https://github.com/OSGeo/grass-addons/tree/grass8/roadmap Is it a candidate for grass-website if we don't want to remove completely?

_Originally posted by @echoix in https://github.com/OSGeo/grass-addons/issues/670#issuecomment-1010067341_

**Comment by wenzeslaus** [comment]
+1 for removing the roadmap directory. Yes, having a nice roadmap would be great, but a directory in source code does not seem to work. So far, flexibility of wiki worked better for v8 planning.

Having it in grass-website translated directly to the website might be of interest to some users (but maybe not many), however having important roadmap planning discussions in PRs to grass-website would be confusing.

**Comment by echoix** [comment]
If you take a look at the contents of the folder, it isn't really a place where things are planned or commented about. It's literally a 3 line README, a bunch of binary pictures with some charts of number of commits up to 2009, and a webpage displaying a dozen screenshots of the look of the GRASS homepage from 1997-2012. Most files there haven't been touched in 13 years.

**Comment by neteler** [comment]
Yes - they are historical artifacts to be kept.
I'll move them to https://github.com/OSGeo/grass-promo/ in the next days incl. the git history.

**Comment by neteler** [comment]
I have moved https://github.com/OSGeo/grass-addons/tree/grass8/roadmap to https://github.com/OSGeo/grass-promo/tree/master/grass-evolution.

History: https://github.com/OSGeo/grass-promo/commit/8e6ade6d851a96926dc358388cca29d6309f1a21
