### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by smirnov111-1** [OSGeo/grass-addons#679]
**Name of the addon**
The name of the GRASS GIS addon.

**Describe the bug**
A clear and concise description of what the bug of the addon is.

**To Reproduce**
3. Compute '....'

**Expected behavior**

**Screenshots**

**System description (please complete the following information):**
 - Operating System: [e.g. Windows, Linux, ... incl. version]
 - GRASS GIS version [e.g. 7.8.1]

**Additional context**

**Comment by veroandreo** [comment]
@smirnov111-1 it seems you created an empty bug report. Note that you can edit this one if you have indeed something to report. Otherwise, please close.
