### ISSUE TITLE
[Question] Keeping Last changed commented in manual pages

### ISSUE THREAD

**Issue by echoix** [OSGeo/grass-addons#684]
Since PRs osgeo/grass#2100, osgeo/grass#2110, osgeo/grass#2111, osgeo/grass#2113,osgeo/grass#2110 added automatic inclusion of dates in the manual pages, I'm asking if newer (addons) manual pages should keep the old `<p> <i>Last changed: $Date$</i>` commented out or remove the HTML comment when updating the pages.

If they are to remove, is it better to remove all of them in one commit (all of them will have the same date), or incrementally when changing files?

I'm still following up on the spelling fixes long-term chore.
Sorry if I chose an issue here to ask even if it's not a bug, I didn't find a better place for this.

**Comment by echoix** [comment]
Perhaps I could use some guidelines, like from @neteler? Is someone else qualified to suggest?

**Comment by neteler** [comment]
For me no longer a need to keep the commented entries.

@ninsbl do you need them or shall we remove them everywhere in core and addons?

If to be removed, then I suggest an all-in-one single commit.

**Comment by echoix** [comment]
Ok, that's good for me! If @ninsbl has the same opinion, we can close this and add this to a better todo list, since it won't be a question anymore, but rather a task to do.

**Comment by ninsbl** [comment]
I dont think they are needed any more. `g.citation` would need some adjustment, but I am on that in #677. So, please go ahead and remove
