### ISSUE TITLE
[Bug] r.random.weight string.replace() 

### ISSUE THREAD

**Issue by Giordano8** [OSGeo/grass-addons#721]
r.random.weight in GRASS GIS.

In python code there should be a bug related to string.replace in line 108

**Screenshots**
Here the bug in GRASS 
![image](https://user-images.githubusercontent.com/102518089/160373839-8b4a15ab-3b04-4132-8d5f-872dc4629246.png)

Here the suspected bug in the python code (lines 87 and 108)
![image](https://user-images.githubusercontent.com/102518089/160374256-e25de131-3259-43c9-9030-609eb551d3dc.png)

A similar fixed bug here https://github.com/OSGeo/grass-addons/commit/f4294b9dcf15be44537e90f042cc1ac0a53a5e59

**Comment by petrasovaa** [comment]
Thanks for catching this, would you be willing to contribute a fix?

**Comment by Giordano8** [comment]
I'm not a grass or python expert, but if it's just a line of code I can try...

**Comment by petrasovaa** [comment]
No need to be expert for this, but let me suggest following https://github.com/OSGeo/grass-addons/blob/grass8/CONTRIBUTING.md, that will help you, especially if you are not super familiar with git/github.
