### ISSUE TITLE
[Bug]  v.centerline: input and output not valid parameter(s) 

### ISSUE THREAD

**Issue by afrigeri** [OSGeo/grass-addons#726]
**Name of the addon**
v.centerline 

**Describe the bug**
A clear and concise description of what the bug of the addon is.

During v.centerline installation we get the WARNING:
```
WARNING: Bug in UI description. Missing module description - module does not 
```
then, the GUI is missing input and output fields.

v.centerline --verbose returns:

```
v.centerline --verbose 
WARNING: Bug in UI description. Missing module description
Traceback (most recent call last):
  File "/home/alf/.grass7/addons/scripts/v.centerline", line 391, in <module>
    main()
  File "/home/alf/.grass7/addons/scripts/v.centerline", line 89, in main
    input = options["input"]
KeyError: 'input'
Searches for GRASS data base files and sets variables for the shell.

Usage:
 g.findfile [-nl] element=string file=string [mapset=string] [--help]
   [--verbose] [--quiet] [--ui]

Flags:
  -n   Do not add quotes
  -l   List available elements and exit

Parameters:
  element   Name of an element
     file   Name of an existing map
   mapset   Name of a mapset (default: search path)

ERROR: Required parameter <file> not set:
	(Name of an existing map)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/alf/.grass7/addons/scripts/v.centerline", line 65, in cleanup
    if grass.find_file(tmp_points_map, element="vector")["name"]:
KeyError: 'name'

```

seems that the script is not getting the g.findfile working ok.

**To Reproduce**
1. Go to grass command line
2. type: v.centerline 

**System description (please complete the following information):**
 - Operating System: Ubuntu 21.10
 - GRASS GIS version 7.8.5

**Additional context**

**Comment by petrasovaa** [comment]
I don't have this issue for GRASS 8, can't test GRASS 7.8 here right now.

**Comment by afrigeri** [comment]
Fired up GRASS8 (docker),  v.centerline downloads from addons repo and works perfectly!

**Comment by petrasovaa** [comment]
Seems like a local issue, please reopen if needed.
