### ISSUE TITLE
[Bug] GRASS GIS addons: ctypes "ImportError: Could not load grass_vector.8.2" and "error while loading shared libraries: libgrass_gis.8.2.dll"

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#771]
**Name of the addon**

All ctypes-related addons on Windows:

https://wingrass.fsv.cvut.cz/grass82/addons/grass-8.2.0/logs/

**Describe the bug**

```
File "C:\msys64\usr\src\grass820\dist.x86_64-w64-mingw32\etc\python\grass\lib\ctypes_loader.py", line 105,
 in __call__
    raise ImportError("Could not load %s." % libname)
ImportError: Could not load grass_vector.8.2.
```

and

```
C:/Users/landamar/grass_packager/grass820/addons/r.stream.segment/bin/r.stream.segment.exe: 
error while loading shared libraries: libgrass_gis.8.2.dll: cannot open shared object file: No such file or directory
```

**To Reproduce**
1. Go to wingrass.fsv.cvut.cz

**Expected behavior**

Restore compilation of numerous addons for winGRASS.

**System description (please complete the following information):**
 - Windows, winGRASS server
 - GRASS GIS version 8.2.0

**Comment by tmszi** [comment]
GRASS GIS issue https://github.com/OSGeo/grass/issues/2497 and https://github.com/OSGeo/grass/issues/2288.

**Comment by neteler** [comment]
@landam I close this in favour of the other reports mentioned above.
