### ISSUE TITLE
"A tile size of 100 m seems to large and produce loss of some spatial units" error on  #r.area.createweight Add-On for GRASS GIS on Ubuntu

### ISSUE THREAD

**Issue by naufalianf** [OSGeo/grass-addons#773]
Hello everyone,

Currently i'm facing some issue when i'm doing dasymetric mapping using #r.area.createweight on my GRASS GIS 7.8.6 that run on Ubuntu 22.04. 

I have entered various required data such as raster and vector by following the steps from the manual. But error appear when i'm running the program

The error say:

> ERROR: A tile size of 100 m seems to large and produces loss of some spatial units. Try to reduce the 'tile_size' parameter or edit the vector to merge,....

I tried to resize the resolution of the "tile" with various sizes, but the error still appears whether I am told to reduce or enlarge it.

![SS_Grass](https://user-images.githubusercontent.com/90570415/184128242-41763ba8-88e5-473e-a415-d8eccefb391e.PNG)

When i try on ubuntu 20.04, error like this still appears as picture down below

![SS_Grass_20_04](https://user-images.githubusercontent.com/90570415/184129302-98260fbf-b16e-4f97-b023-c367e53e906c.PNG)

Is there something that i missed or is there a problem on ubuntu

Please, i really need your advice, if there any solution for this

**Comment by tmszi** [comment]
Did @naufalianf solve this issue please?

**Comment by naufalianf** [comment]
Hello @tmszi, sorry it turns out that the error is in the data i use, I'm still looking for whats the difference in the data that causes this error to appear. Thanks for the reply!

**Comment by tmszi** [comment]
> Hello @tmszi, sorry it turns out that the error is in the data i use, I'm still looking for whats the difference in the data that causes this error to appear. Thanks for the reply!

Could you upload your location with maps which is inputs for r.area.createweight module, please (if it is possible)?

1. Launch GRASS GIS with your LOCATION and MAPSET which has only maps for your analysis (r.area.createweight module)
2. Create archive and upload to [transfer.sh](https://transfer.sh/) service with command bellow

Example: 

```
GRASS worldlocation/user1:~ > ARCHIVE=/tmp/data.tar.xz MAPSET_PATH="$(g.gisenv get=GISDBASE)/$(g.gisenv get=MAPSET)" tar -cvJf $ARCHIVE $MAPSET_PATH && curl --upload-file $ARCHIVE  https://transfer.sh/data.tar.xz
```
3. After you upload your MAPSET archive (command above) you get link (on the terminal) something like that `https://transfer.sh/tR0Hu2/data.tar.xz` for download your archive and you could send me this link, please.
