### ISSUE TITLE
[Wish] Register all addon keywords in main Keywords Index of all GRASS GIS modules

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#776]
**Describe the wish**

So far the keywords of GRASS GIS addons are not yet added to (injected):

`Keywords - Index of GRASS GIS modules`
https://grass.osgeo.org/grass-stable/manuals/keywords.html

This being solved during addon compilation would greatly increase the visibility of the GRASS GIS [addons](https://grass.osgeo.org/grass-stable/manuals/addons/).

**Comment by tmszi** [comment]
Close by #780 and https://github.com/OSGeo/grass/pull/2529.
