### ISSUE TITLE
Configure and Makefile issues

### ISSUE THREAD

**Issue by bhlevca** [OSGeo/grass-addons#784]
The Readme instructions are outdated or code is not complete

```
./configure # [optionally flags]
make libs
```
None of above commands works. There is no configure script or Makefile. 

There is only one Makefile in the 'src' directory that can only build the extensions

**Comment by neteler** [comment]
> None of above commands works. There is no configure script or Makefile.

I agree, the original text is confusing.
Please check my attempt to clarify the instructions in #785 (suggest changes therein as needed).

**Comment by neteler** [comment]
I have restructured the `README.md`. Please check if anything is yet unclear - if so, please report.
