### ISSUE TITLE
manual: keyword index URLs partially broken

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#791]
Some links at are still partially broken:
https://grass.osgeo.org/grass82/manuals/keywords.html

> > @tmszi seems a double `//` leaks in somewhere, only discovered that now.
> 
> I cleaned up the local server patches, updated and recompiled.
> 
> This effect only happens with the "grass-stable" redirects:
> 
> https://grass.osgeo.org/grass-stable/manuals/addons/d.vect.colbp.html --> https://grass.osgeo.org/grass82//manuals/addons/d.vect.colbp.html
> 
> Probably it is an issue of the Apache redirect (but I think to not have seen it before).

I found `//` in URL here https://grass.osgeo.org/grass82//manuals/index.html

Some links also contain the grass.osgeo.org server setup related internal directory names.
Not sure if Apache redirects interfere or the local setup (see https://github.com/OSGeo/grass-addons/tree/grass8/utils/cronjobs_osgeo_lxd#web-site-organisation).

_Originally posted by @tmszi in https://github.com/OSGeo/grass-addons/issues/780#issuecomment-1242351689_

**Comment by tmszi** [comment]
> Some links at are still partially broken: https://grass.osgeo.org/grass82/manuals/keywords.html

Yes you are right, core modules links still use absolute path instead of relative path, fixed with https://github.com/OSGeo/grass/pull/2574.
