### ISSUE TITLE
[Bug] r.in.nasadem runs with wrong password

### ISSUE THREAD

**Issue by gheetpass** [OSGeo/grass-addons#821]
**Name of the addon**
r.in.nasadem

**Describe the bug**
r.in.nasadem starts running with wrong password but gives an error for other reasons so that it is not apparent that the error occured because of the wrong password.

**To Reproduce**
1. Run r.in.nasadem user=USER password=PASSWORD ...  but insert a wrong password.
2. See error

**Expected behavior**
r.in.nasasdem does not run with wrong password input / produces error because of wrong password 

**System description:**
- Operating System: Linux
- GRASS GIS version 8.2.1

**Comment by neteler** [comment]
The problem seems to be the `pass` here:

https://github.com/OSGeo/grass-addons/blob/ee8fbcb1a06f57d6197b6a11d327dca8289fda89/src/raster/r.in.nasadem/r.in.nasadem.py#L304
