### ISSUE TITLE
np.float/numpy.float does not exist in numpy 1.24.1

### ISSUE THREAD

**Issue by kirimaru-jp** [OSGeo/grass-addons#856]
`np.float`(`numpy.float`) does not exist in the newest version [numpy 1.24.1](https://pypi.org/project/numpy/), hence it could lead to errors when using `i.sentinel.import` (just happened to me).
```
>>> numpy.float
Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "~/.local/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'
```

`np.float`(`numpy.float`) is used 4 times between lines 830 and 850:
https://github.com/OSGeo/grass-addons/blob/f17c792f5de56c64ecfbe63ec315307872cf9d5c/src/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py#L830-L850

A solution is to replace `np.float` by `np.float32` (or `np.float64`/`np.double`).

**Comment by ninsbl** [comment]
Thanks for the heads-up @kirimaru-jp 
Would you be willing to submit a pull request?

**Comment by kirimaru-jp** [comment]
> Thanks for the heads-up @kirimaru-jp Would you be willing to submit a pull request?

Yes, I [did](https://github.com/OSGeo/grass-addons/pull/857). 
I replaced `np.float` by `float` in 4 files, since [`np.float` is a deprecated alias for python `float` type](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated).

**Comment by neteler** [comment]
Thanks for your efforts!

> I replaced `np.float` by `float` in 4 files, since [`np.float` is a deprecated alias for python `float` type](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated).

BTW: in grass-core there are also a few of those... (in case you are willing to submit a pull request also there).
