### ISSUE TITLE
[Bug] Deprecate r.in.pdal Python addon script

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#867]
**Name of the addon**

The addon repository still contains the old `r.in.pdal` Python addon script (https://grass.osgeo.org/grass82/manuals/addons/r.in.pdal.html) which may lead to confusion.

**Describe the bug**

The presence of the script generates confusion with the C implementation in GRASS-core.

Suggestion:

Deprecate the script, at least, do not compile it any more for the addon overview page.

**Comment by wenzeslaus** [comment]
What do you mean by deprecate? You can add "Deprecated, use r.in.pdal core module" at the end of module description line. ...or some other wording, we don't really use "core" outside of development. This way it does not break anything, but it is clear it is deprecated and we don't have to build a specific mechanism to ignore modules (they are not picked by directory, not manually specified as was the case in the past if I recall correctly).

**Comment by neteler** [comment]
> What do you mean by deprecate?

I mean that the r.in.pdal Python addon must no longer show up on the overview page https://grass.osgeo.org/grass82/manuals/addons/ - it is slow, comes with partially different interface and confuses ppl.

I have addressed it in #868
