### ISSUE TITLE
[Bug] parameter name conflict between i.zc and the GridModule class in pygrass

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#87]
**Name of the addon**
i.cutlines

**Describe the bug**
As per manual, there is a parameter name conflict between i.zc and the GridModule class in pygrass.
Until this is resolved tiled edge detection is only possible with i.edge. 

Question: can the conflict (which precisely, @mlennert ?) be fixed?

**Comment by mlennert** [comment]
This was a problem only until GRASS 7.4. I've indicated it as such in the manual now [913f581]. Since then, the issue was solved in the grid module (https://github.com/OSGeo/grass/commit/6294dbfe9d05c77363a6b43b93ad75f0aedfea7c).
