### ISSUE TITLE
[Bug] i.sentinel.import deletes the unzipped folder without any warning

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-addons#90]
**Name of the addon**
i.sentinel.import

**Describe the bug**
`i.sentinel.import` erases the unzipped folder after writing the metadata to the imported bands. That "new" (maybe only for me) behaviour forces the users to unzip again if they want to use `i.sentinel.mask` just after the import, because they need to pass the MTD_TL.xml file. This was not the behaviour with an (older?) i.sentinel version, when I started working in this workflow a couple of weeks ago, i.e., in my office computer, it does not remove the unzipped file.

Is it possible to at least warn the user that the unzipped folder will be removed, or set this behaviour as optional with a flag?

Ideally, `i.sentinel.mask` could read the metadata written into the imported bands directly, then we wouldn't need to pass the MTD_TL.xml file.

**Comment by neteler** [comment]
I suggest to have a "keep ZIP file(s)" flag.

The flag can then be used here:

https://github.com/OSGeo/grass-addons/blob/2f05e5b4d2bcd863e7c9675acaefe869575ddf24/grass7/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py#L77

@ninsbl , @landam any opinion?

**Comment by ninsbl** [comment]
No objections. A flag could be a simple solution.

The reason for this bug report will however be addressed with #137, no?

Most elegant / efficient would be probably to never unzip but use [GDALs virtual file system](https://gdal.org/user/virtual_file_systems.html) and adding `/vsizip/`in front of import paths (at least when data is not just linked)...

**Comment by veroandreo** [comment]
The problem reported is that i.sentinel.import deletes the unzipped directories, not the zip file. Hence when using it together with i.sentinel.mask one needs to go through unzipping once again. Ideally we should have a flag then to keep the unzipped files.

If you never unzip by using the gdal vsizip as suggested, how would you then find the metadata file needed for i.sentinel.mask?? Does it also allow to read other types of files? Seems to me the unzipping is needed, or much better, a way to write and read the relevant info for `i.sentinel.mask` somewhere else, so we don't need that metadata file anymore.

**Comment by ninsbl** [comment]
#137 writes metadata to json and allows to read that json in i.sentinel.mask. so with that PR merged there should be no more need to keep the unzipped safe. That said the metadata file could also be read directly from zip file...

**Comment by lucadelu** [comment]
@veroandreo could this issue be closed?

**Comment by veroandreo** [comment]
yes, closing
