### ISSUE TITLE
Building of addons for WinGRASS 7.6.x

### ISSUE THREAD

**Issue by NikosAlexandris** [OSGeo/grass-addons#94]
What is the (new?) policy for building Add-ons for Windows? I.e., how often, when  and where is it documented?  (I never recall easily where the build process/script is documented/placed, but I know there is one :-)).

The builds in https://wingrass.fsv.cvut.cz/grass76/x86_64/addons/latest/ are old (dated 2019-09-02). The parent directory, however, is dated
>`grass-7.6.1/	2020-02-23 09:07`

Does this mean that if someone wants to install version 7.6.x, he won't get the latest Add-ons via the `g.extensions` installer?

**Comment by hellik** [comment]
See for documentation:

https://github.com/landam/wingrass-maintenance-scripts?files=1

>how often, when

once a day

**Comment by hellik** [comment]
See

https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/

**Comment by NikosAlexandris** [comment]
> See
> 
> https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/

I am asking for 7.6.x though.

ps- 7.8.x does not _play_ under Windows via the OSGeo4W installer.

**Comment by neteler** [comment]
@landam could you please enlighten us?

**Comment by landam** [comment]
There are no operational Windows builds for 7.6.x.

**Comment by landam** [comment]
@NikosAlexandris What do you mean by "ps- 7.8.x does not play under Windows 10 via the OSGeo4W installer" ?

**Comment by NikosAlexandris** [comment]
> @NikosAlexandris What do you mean by "ps- 7.8.x does not play under Windows 10 via the OSGeo4W installer" ?

https://github.com/OSGeo/grass/issues/371

**Comment by neteler** [comment]
> There are no operational Windows builds for 7.6.x.

I am afraid that this report is "wontfix" since we don't have the resources to also maintain 7.6.x addons besides 7.8.x.
