### ISSUE TITLE
[Bug] v.surf.nnbathy:  NameError: `StandardError` is not defined

### ISSUE THREAD

**Issue by mxkpp** [OSGeo/grass-addons#941]
**Name of the addon**
v.surf.nnbathy

**Describe the bug**
When calling this extension via Python 3, a NameError exception is raised when trying to catch exception type StandardError.  I believe this was a built-in exception type in Python 2 but was removed from Python 3.

**To Reproduce**
1. Install v.surf.nnbathy into a Python 3 GRASS environment.
2. Call gs.run_command("v.surf.nnbathy", ...) in a way that triggers this except block:
https://github.com/OSGeo/grass-addons/blob/9a7716657dc3b0951b56a2015f4bfd66438907eb/src/vector/v.surf.nnbathy/nnbathy.py#L210

**Expected behavior**
Exception handling would succeed.

**System description (please complete the following information):**

- Operating System: Ubuntu 20.04.6 LTS (Docker image "mundialis/grass-py3-pdal:7.8.8-ubuntu") running in conda environment installed via "https://repo.anaconda.com/miniconda/Miniconda3-py310_23.5.2-0-Linux-x86_64.sh"
- GRASS GIS version 7.8.8

**Comment by neteler** [comment]
Please note that the GRASS GIS 7 addons are available in a different branch ("grass7/"):

https://github.com/OSGeo/grass-addons/blob/grass7/src/vector/v.surf.nnbathy/nnbathy.py

Can you try that first? (of course the recommendation is to use GRASS GIS 8).

**Comment by mxkpp** [comment]
Yes, that's the branch I took the permalink from.  It's the same in the grass8 branch too though.  Unless this is supposed to run in Python 2, I don't see how it could work if StandardError is not in the Python 3 namespace.

**Comment by tmszi** [comment]
According [doc](https://portingguide.readthedocs.io/en/latest/exceptions.html?highlight=StandardError#the-removed-standarderror) for porting Python 2 code to version 3: _"The recommended fixer will replace all uses of `StandardError` with `Exception`. Review the result to check if this is correct"_.

Could @mxkpp share full Python command for running v.surf.nnbathy module, please?

**Comment by mxkpp** [comment]
Sorry for the delay.  Below is the way the `v.surf.nnbathy` module is being invoked.  Unfortunately I'm not able to share input data or more of the code context (though I don't think that is necessary to see how the existing module would have a problem in Python 3).

```python3
from grass_session import Session
import grass.script as gs

gs.set_raise_on_error(True)
gs.set_capture_stderr(True)

session_args = {"gisdb": "/app/data/grassdata/foobar", "location": "foobar", "mapset": "PERMANENT", "create_opts": ""}

with Session(**session_args):
    gs.run_command(
            "v.surf.nnbathy",
            input_="input_foobar",
            output="output_foobar",
            column="column_foobar",
            algorithm="nn",
            overwrite="true"
        )
```

**Comment by wenzeslaus** [comment]
Fix is now in #981. @mxkpp or @rmarzocchi84 if you want to give thumbs up for the PR or even pick up implementing an actual fix or fixing some of the Pylint warnings, this would be a good time. In any case, #981 can be merged soon.

**Comment by mxkpp** [comment]
Thanks all, I did not get a chance to look but I see it was merged into grass8 branch.  btw it affects grass7 too (and maybe others), anything using Python 3.

**Comment by wenzeslaus** [comment]
If you want to update it for v7 or anything else, please open an PR and feel free to cherry pick (git cherry-pick) the commit from grass8 branch. We will be happy to merge it, but we can't go beyond that in supporting the legacy version given the resources we have at our disposal.

**Comment by mxkpp** [comment]
@wenzeslaus understood. I'd be glad to revisit and open a PR when I'm able.
