### ISSUE TITLE
v.rast.move: empty keywords break addon overview script

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-addons#950]
The cronjob to generate addons struggles with

https://github.com/OSGeo/grass-addons/blob/7a3dfb74e3827a3960a761060449f2ddaf3503e8/src/vector/v.rast.move/v.rast.move.py#L22

`Empty keyword from file v.rast.move.html line: <a href="../vector.html">vector</a>, <a href="../topic_.html"></a>, <a href="../topic_.html"></a>, <a href="../topic_.html"></a>
`

At least three keywords are needed:
- module family
- topic
- specific keyword(s)
-

**Comment by wenzeslaus** [comment]
I'll fix the keywords. Only one is of course wrong and it should be checked by the CI for both core and addons.

But how did you even find that? Is something broken? I see success in Linux logs. Windows logs seem broken but for a different reason. They are from 24 Jun 2023 (v.rast.move is from July 18).

**Comment by neteler** [comment]
> But how did you even find that? 

I happened to run the script in a terminal to test #951

> Is something broken?

No idea. The script seems (?) to stop at that step but I have no time to investigate.
