### ISSUE TITLE
v.surf.mass: Input should be vector "area" map?

### ISSUE THREAD

**Issue by HuidaeCho** [OSGeo/grass-addons#968]
@metzm The `input` option of `v.surf.mass` says `Name of input vector point map`, but I think it should be `Name of input vector area map`?

**Comment by wenzeslaus** [comment]
Given lines like `G_fatal_error(_("No areas in input vector <%s>"), in_opt->answer);` and `for (i = 1; i <= nareas; i++) {...if (Vect_get_area_cats(&In, i, Cats)` I think "area" is correct. I would almost say that the default description should be sufficient, but this has also an optional input and the type of features expected in the input is actually something we should make more prominent.
